DROP DATABASE IF EXISTS quiz;
CREATE DATABASE quiz;
USE quiz;
CREATE TABLE curso (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    sigla VARCHAR(10)
);
CREATE TABLE disciplina (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    modulo int not null,
    sigla VARCHAR(20),
    id_curso INT,
    FOREIGN KEY (id_curso) REFERENCES curso(id) ON DELETE
    SET
        NULL ON UPDATE CASCADE
);
CREATE TABLE usuario (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    pontuacao INT DEFAULT 0
);
CREATE TABLE questao (
    id INT AUTO_INCREMENT PRIMARY KEY,
    enunciado TEXT NOT NULL,
    pontuacao INT,
    id_disciplina INT,
    FOREIGN KEY (id_disciplina) REFERENCES disciplina(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE alternativa (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_questao INT,
    perguntas VARCHAR(255) NOT NULL,
    correta TINYINT(1) DEFAULT 0,
    FOREIGN KEY (id_questao) REFERENCES questao(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE quiz (
    id INT AUTO_INCREMENT PRIMARY KEY,
    data DATE NOT NULL,
    id_usuario INT,
    id_disciplina INT,
    id_questao_01 INT,
    id_questao_02 INT,
    id_questao_03 INT,
    id_questao_04 INT,
    id_questao_05 INT,
    pontuacao INT DEFAULT 0,
    FOREIGN KEY (id_usuario) REFERENCES usuario(id) ON UPDATE CASCADE ON DELETE
    SET
        NULL,
        FOREIGN KEY (id_disciplina) REFERENCES disciplina(id) ON UPDATE CASCADE ON DELETE
    SET
        NULL,
        FOREIGN KEY (id_questao_01) REFERENCES questao(id) ON UPDATE CASCADE ON DELETE
    SET
        NULL,
        FOREIGN KEY (id_questao_02) REFERENCES questao(id) ON UPDATE CASCADE ON DELETE
    SET
        NULL,
        FOREIGN KEY (id_questao_03) REFERENCES questao(id) ON UPDATE CASCADE ON DELETE
    SET
        NULL,
        FOREIGN KEY (id_questao_04) REFERENCES questao(id) ON UPDATE CASCADE ON DELETE
    SET
        NULL,
        FOREIGN KEY (id_questao_05) REFERENCES questao(id) ON UPDATE CASCADE ON DELETE
    SET
        NULL
);
INSERT INTO curso (id, nome, sigla) VALUES
(1, 'Desenvolvimento de Sistemas', 'DS');

INSERT INTO disciplina (id, nome, modulo, sigla, id_curso) VALUES
(1, 'Programação e Algoritmos', 1, 'PA', 1),
(2, 'Banco de Dados I', 1, 'BD1', 1),
(3, 'Análise e Projeto de Sistemas', 1, 'APS', 1),
(4, 'Design Digital', 1, 'DD', 1),
(5, 'Programação Web I', 1, 'PW1', 1),
(6, 'Fundamentos da Informática', 1, 'FI', 1),
(7, 'Técnicas de Programação', 1, 'TP', 1),
(8, 'Desenvolvimento de Sistemas', 1, 'DS', 1),
(9, 'Banco de Dados II', 2, 'BD2', 1),
(10, 'Internet e Protocolos', 2, 'IP', 1),
(11, 'Programação de Aplicativos Mobile I', 2, 'PAM1', 1),
(12, 'Programação Web II', 2, 'PW2', 1),
(13, 'Segurança de Sistemas da Informação', 3, 'SSI', 1),
(14, 'Banco de Dados III', 3, 'BD3', 1),
(15, 'Sistemas Embarcados', 2, 'SE', 1),
(16, 'Programação de Aplicativos Mobile II', 3, 'PAM2', 1),
(17, 'Programação Web III', 3, 'PW3', 1),
(18, 'Qualidade e Teste de Software', 3, 'QTS', 1),
(20, 'Inglês Instrumental', 1, 'II', 1),
(21, 'Ética e Cidadania Organizacional', 1, 'ECO', 1),
(22, 'Operação de Software Aplicativo', 1, 'OSA', 1),
(23, 'Linguagem, Trabalho e Tecnologia', 3, 'LTT', 1),
(24, 'Desenvolvimento de Sistemas II', 3, 'DS2', 1);

INSERT INTO questao (id, enunciado, pontuacao, id_disciplina) VALUES
(106, 'O que é um algoritmo?', 10, 1),
(342, 'O que é pseudocódigo?', 10, 1),
(107, 'O que é uma variável?', 10, 1),
(108, 'O que é uma constante?', 10, 1),
(109, 'O que é uma IDE?', 10, 1),
(110, 'O que significa “depuração”?', 10, 1),
(111, 'Qual a função do comando if/else?', 20, 1),
(343, 'O que é função em programação?', 20, 1),
(112, 'O que é laço de repetição?', 20, 1),
(113, 'O que é teste de mesa?', 20, 1),
(114, 'O que é programação modular?', 20, 1),
(115, 'O que é recursividade?', 20, 1),
(116, 'Qual a diferença entre compilador e interpretador?', 30, 1),
(344, 'O que é complexidade de algoritmo?', 30, 1),
(117, 'O que é pilha de chamadas (call stack)?', 30, 1),
(118, 'O que é tratamento de exceções?', 30, 1),
(119, 'O que é vetor?', 30, 1),
(120, 'O que é matriz?', 30, 1),
(91, 'O que é um banco de dados?', 10, 2),
(92, 'O que significa SQL?', 10, 2),
(93, 'Para que serve uma tabela em banco de dados?', 10, 2),
(339, 'O que é um campo em banco de dados?', 10, 2),
(94, 'O que é uma chave primária?', 10, 2),
(95, 'Cite um sistema gerenciador de banco de dados relacional (SGBDR).', 10, 2),
(96, 'Diferença entre DELETE e DROP:', 20, 2),
(97, 'O que é relacionamento entre tabelas?', 20, 2),
(340, 'Qual comando SQL insere dados em uma tabela?', 20, 2),
(98, 'Qual a função do comando SELECT?', 20, 2),
(99, 'O que é modelagem de dados?', 20, 2),
(100, 'O que é chave estrangeira?', 20, 2),
(101, 'Diferença entre bancos relacionais e não relacionais:', 30, 2),
(102, 'O que é normalização de banco de dados?', 30, 2),
(103, 'Como funciona um JOIN em SQL?', 30, 2),
(341, 'O que é transação em banco de dados?', 30, 2),
(104, 'Importância da integridade referencial:', 30, 2),
(105, 'Etapas para criar modelo lógico de banco de dados:', 30, 2),
(121, 'O que é um requisito funcional em um sistema?', 10, 3),
(122, 'Qual metodologia abaixo é considerada ágil?', 10, 3),
(123, 'Qual ferramenta pode ser usada para organização de tarefas em Kanban?', 10, 3),
(124, 'Quem remove impedimentos no Scrum?', 10, 3),
(345, 'O que é um requisito não funcional?', 10, 3),
(346, 'Qual artefato é usado para representar casos de uso?', 10, 3),
(125, 'O ciclo de vida de um sistema representa:', 10, 3),
(126, 'Qual alternativa apresenta apenas tipos de requisitos?', 20, 3),
(127, 'O Backlog do Produto no Scrum é:', 20, 3),
(128, 'A UML é utilizada para:', 20, 3),
(129, 'O principal objetivo do Design Sprint é:', 20, 3),
(347, 'O que é prototipação de sistemas?', 20, 3),
(348, 'Qual evento do Scrum ocorre diariamente?', 20, 3),
(130, 'Uma característica do modelo em cascata é:', 20, 3),
(131, 'Qual evento do Scrum é destinado à avaliação do trabalho concluído ao final da Sprint?', 30, 3),
(132, 'Ferramentas CASE possuem como principal objetivo:', 30, 3),
(133, 'Qual princípio do Manifesto Ágil valoriza mais as pessoas?', 30, 3),
(134, 'No Kanban, o principal objetivo é:', 30, 3),
(135, 'O Product Owner é responsável por:', 30, 3),
(349, 'O que significa o conceito de "incremento" no Scrum?', 30, 3),
(31, 'O que é uma imagem raster (bitmap)?', 10, 4),
(327, 'O que é resolução de imagem?', 10, 4),
(32, 'Qual formato é comum para imagens raster?', 10, 4),
(33, 'O que é uma imagem vetorial?', 10, 4),
(34, 'Qual formato é comum para imagens vetoriais?', 10, 4),
(35, 'O que significa CMYK?', 10, 4),
(36, 'O que significa RGB?', 20, 4),
(37, 'O que é prototipação de interfaces?', 20, 4),
(38, 'O que é tipografia?', 20, 4),
(39, 'O que é Gestalt no design?', 20, 4),
(40, 'O que é transparência em imagens digitais?', 20, 4),
(328, 'O que é mockup em design?', 20, 4),
(41, 'O que é HEXADECIMAL em design digital?', 30, 4),
(42, 'O que é um wireframe?', 30, 4),
(43, 'O que é um pictograma?', 30, 4),
(44, 'O que é um banco de imagens?', 30, 4),
(329, 'O que é UI Design?', 30, 4),
(45, 'O que é prototipagem de alta fidelidade?', 30, 4),
(46, 'Qual a função da tag <p> em HTML?', 10, 5),
(47, 'Qual a função da tag <img>?', 10, 5),
(48, 'Qual a função da tag <a>?', 10, 5),
(330, 'Qual a função da tag <h1> em HTML?', 10, 5),
(49, 'Qual a função da propriedade CSS color?', 10, 5),
(50, 'Qual a função da propriedade CSS background-color?', 10, 5),
(51, 'Qual a função da tag <form> em HTML?', 20, 5),
(52, 'Qual a função da tag <table>?', 20, 5),
(53, 'Qual a função do comando document.getElementById() em', 20, 5),
(54, 'Qual a função da estrutura if/else em JavaScript?', 20, 5),
(55, 'Qual a função do Box Model em CSS?', 20, 5),
(331, 'Qual a função da propriedade CSS margin?', 20, 5),
(56, 'Qual a função do Flexbox em CSS?', 30, 5),
(57, 'Qual a função do Grid Layout em CSS?', 30, 5),
(58, 'O que significa async/await em JavaScript?', 30, 5),
(332, 'O que significa AJAX em programação web?', 30, 5),
(59, 'Qual a função do JSON em JavaScript?', 30, 5),
(60, 'Qual a função do GitHub Pages?', 30, 5),
(61, 'O que é hardware?', 10, 6),
(333, 'O que é processador?', 10, 6),
(62, 'O que é software?', 10, 6),
(63, 'Qual destes é um sistema operacional?', 10, 6),
(64, 'O que é memória RAM?', 10, 6),
(65, 'Qual destes é um periférico de entrada?', 10, 6),
(66, 'O que é representação binária?', 20, 6),
(67, 'O que é software livre?', 20, 6),
(334, 'O que é firewall?', 20, 6),
(68, 'O que é virtualização?', 20, 6),
(69, 'O que é rede local (LAN)?', 20, 6),
(70, 'O que é computação em nuvem?', 20, 6),
(71, 'Qual comando do Windows em linha de comando exibe o conteúdo de', 30, 6),
(335, 'O que é virtual private network (VPN)?', 30, 6),
(72, 'Qual comando do Linux em linha de comando exibe o conteúdo de um', 30, 6),
(73, 'Qual comando do Windows em linha de comando muda de diretório?', 30, 6),
(74, 'Qual comando do Linux em linha de comando mostra o diretório atual?', 30, 6),
(75, 'O que é Internet das Coisas (IoT)?', 30, 6),
(136, 'O que é um objeto na programação orientada a objetos?', 10, 8),
(137, 'Qual elemento é utilizado para armazenar características de um objeto?', 10, 8),
(138, 'O padrão MVC é utilizado para:', 10, 8),
(139, 'Qual operação CRUD é responsável por excluir dados?', 10, 8),
(350, 'O que é um método em programação orientada a objetos?', 10, 8),
(140, 'Qual componente gráfico permite selecionar apenas uma opção entre várias?', 10, 8),
(141, 'O encapsulamento na programação orientada a objetos serve para:', 20, 8),
(142, 'A herança permite que uma classe:', 20, 8),
(143, 'O DAO é um padrão utilizado para:', 20, 8),
(351, 'O que é interface em programação?', 20, 8),
(144, 'Consultas parametrizadas ajudam principalmente na:', 20, 8),
(145, 'O polimorfismo permite que:', 20, 8),
(146, 'A sobrecarga de métodos ocorre quando:', 30, 8),
(352, 'O que é inversão de dependência?', 30, 8),
(147, 'Classes abstratas possuem como característica principal:', 30, 8),
(148, 'Qual alternativa representa corretamente uma vantagem do padrão MVC?', 30, 8),
(149, 'Namespaces são utilizados para:', 30, 8),
(150, 'A sobrescrita de métodos acontece quando:', 30, 8),
(151, 'O principal objetivo do TCC é:', 10, 8),
(152, 'Qual item pode ser considerado uma técnica de pesquisa?', 10, 8),
(153, 'O cronograma de trabalho serve para:', 10, 8),
(154, 'A justificativa em um projeto responde principalmente à pergunta:', 10, 8),
(155, 'Qual documento pode ser utilizado na pesquisa de campo?', 10, 8),
(156, 'A pesquisa bibliográfica é classificada como:', 20, 8),
(157, 'Um dos critérios para escolha do tema do TCC é:', 20, 8),
(158, 'O objetivo geral de um projeto define:', 20, 8),
(159, 'A problematização em um TCC está relacionada com:', 20, 8),
(160, 'O fichamento é utilizado para:', 20, 8),
(161, 'A construção de hipóteses em um projeto tem como finalidade:', 30, 8),
(162, 'A identificação de lacunas no setor profissional significa:', 30, 8),
(163, 'A análise de pertinência, relevância e viabilidade é utilizada para:', 30, 8),
(164, 'Qual alternativa representa um exemplo de documentação direta?', 30, 8),
(165, 'A relação entre TCC e empreendedorismo é importante porque:', 30, 8),
(166, 'O que é um cronograma de atividades?', 10, 8),
(167, 'Qual é a função de um relatório técnico?', 10, 8),
(168, 'O que é um fluxograma?', 10, 8),
(169, 'O referencial teórico de uma pesquisa é formado por:', 10, 8),
(359, 'O que é objetivo específico em um TCC?', 10, 8),
(170, 'O que significa metodologia em um projeto?', 10, 8),
(171, 'A tabulação de dados consiste em:', 20, 8),
(172, 'O objetivo da análise de dados é:', 20, 8),
(173, 'O dimensionamento de recursos serve para:', 20, 8),
(174, 'Qual é a finalidade de um gráfico em relatórios?', 20, 8),
(360, 'O que é metodologia científica em um TCC?', 20, 8),
(175, 'Sistemas de gerenciamento de projetos ajudam a:', 20, 8),
(176, 'A formatação de trabalhos acadêmicos é importante para:', 30, 8),
(361, 'O que é referencial teórico em um TCC?', 30, 8),
(177, 'O processo de codificação de dados em pesquisas consiste em:', 30, 8),
(178, 'O empreendedorismo em projetos de tecnologia envolve:', 30, 8),
(179, 'Um memorial descritivo é um documento utilizado para:', 30, 8),
(180, 'A apresentação oral de um TCC deve priorizar:', 30, 8),
(181, 'Qual linguagem SQL é utilizada para manipulação de dados?', 10, 9),
(182, 'Qual comando é utilizado para inserir dados em uma tabela?', 10, 9),
(183, 'O comando SELECT pertence à categoria:', 10, 9),
(184, 'Qual comando remove dados de uma tabela?', 10, 9),
(185, 'O COMMIT em uma transação serve para:', 10, 9),
(353, 'Qual comando cria uma nova tabela?', 10, 9),
(186, 'O UPDATE é utilizado para:', 20, 9),
(187, 'A cláusula ORDER BY é utilizada para:', 20, 9),
(354, 'Qual cláusula SQL agrupa registros para funções agregadas?', 20, 9),
(188, 'Qual função agregada é utilizada para contar registros?', 20, 9),
(189, 'O INNER JOIN é utilizado para:', 20, 9),
(190, 'O ROLLBACK em transações serve para:', 20, 9),
(191, 'Qual propriedade ACID garante que uma transação seja concluída totalmente ou', 30, 9),
(192, 'O LEFT JOIN retorna:', 30, 9),
(355, 'O que é normalização avançada (3FN)?', 30, 9),
(193, 'O CROSS JOIN gera:', 30, 9),
(194, 'Qual operação SQL combina resultados de duas consultas eliminando duplicidades?', 30, 9),
(195, 'A propriedade de durabilidade no ACID garante que:', 30, 9),
(241, 'O que significa a sigla IP?', 10, 10),
(242, 'Qual protocolo é utilizado para navegação na web?', 10, 10),
(243, 'Qual ferramenta é usada para testar conectividade entre computadores?', 10, 10),
(244, 'O DNS é responsável por:', 10, 10),
(245, 'Qual protocolo é utilizado para acesso remoto seguro?', 10, 10),
(367, 'Qual protocolo é usado para envio seguro de e-mails?', 10, 10),
(368, 'O protocolo HTTPS adiciona qual camada de segurança?', 10, 10),
(246, 'O modelo cliente/servidor funciona quando:', 20, 10),
(247, 'O protocolo TCP é conhecido por:', 20, 10),
(248, 'Qual ferramenta exibe configurações de rede no Windows?', 20, 10),
(369, 'Qual comando no Windows mostra conexões ativas da rede?', 20, 10),
(370, 'Qual código HTTP indica redirecionamento permanente?', 20, 10),
(249, 'O NAT é utilizado para:', 20, 10),
(250, 'Cookies em HTTP servem para:', 20, 10),
(251, 'O HTTPS utiliza quais protocolos para segurança?', 30, 10),
(252, 'O código de status HTTP 404 indica:', 30, 10),
(371, 'Qual protocolo é usado para resolução reversa de nomes?', 30, 10),
(253, 'O protocolo UDP se diferencia do TCP porque:', 30, 10),
(254, 'O Wireshark é utilizado para:', 30, 10),
(255, 'O conceito de Stateless no HTTP significa que:', 30, 10),
(211, 'Qual plataforma é utilizada para desenvolvimento nativo de aplicativos Android?', 10, 11),
(212, 'O Flutter é um modelo de desenvolvimento:', 10, 11),
(356, 'Qual linguagem é usada para desenvolvimento nativo em iOS?', 10, 11),
(213, 'Qual componente é utilizado para exibir textos em aplicativos mobile?', 10, 11),
(214, 'O SDK em desenvolvimento mobile é utilizado para:', 10, 11),
(215, 'As lojas de aplicativos servem para:', 10, 11),
(216, 'O React Native é considerado um modelo de desenvolvimento:', 20, 11),
(217, 'O armazenamento offline em aplicativos permite:', 20, 11),
(218, 'A função das permissões em aplicativos mobile é:', 20, 11),
(357, 'Qual recurso permite enviar notificações para usuários?', 20, 11),
(219, 'A splash screen é:', 20, 11),
(220, 'Navegação e roteamento em aplicativos mobile servem para:', 20, 11),
(221, 'Qual alternativa apresenta apenas tecnologias híbridas?', 30, 11),
(358, 'O que é armazenamento em nuvem em aplicativos mobile?', 30, 11),
(222, 'O gerenciamento de estado dos componentes é importante porque:', 30, 11),
(223, 'Emuladores no desenvolvimento mobile são utilizados para:', 30, 11),
(224, 'O ciclo de vida de um aplicativo mobile representa:', 30, 11),
(225, 'Qual alternativa representa corretamente uma vantagem do desenvolvimento', 30, 11),
(372, 'O que significa IDS?', 10, 13),
(373, 'Qual ferramenta é usada para escanear portas de rede?', 10, 13),
(226, 'O que significa o termo NoSQL?', 10, 14),
(227, 'Qual banco de dados é baseado em documentos?', 10, 14),
(362, 'Qual banco NoSQL é especializado em grafos?', 10, 14),
(363, 'Em bancos NoSQL, o termo "sharding" refere-se a:', 10, 14),
(228, 'O Redis é um exemplo de banco de dados do tipo:', 10, 14),
(229, 'Qual banco de dados é especializado em grafos?', 10, 14),
(230, 'CRUD representa operações de:', 10, 14),
(374, 'Qual técnica de ataque explora confiança do usuário?', 20, 13),
(375, 'Qual protocolo garante comunicação segura na web?', 20, 13),
(231, 'Qual é uma das principais motivações do uso de bancos NoSQL?', 20, 14),
(232, 'Em MongoDB, coleções são equivalentes a:', 20, 14),
(233, 'O modelo Embedded em MongoDB consiste em:', 20, 14),
(234, 'Qual recurso é utilizado para melhorar o desempenho de buscas em bancos de', 20, 14),
(235, 'O Map-Reduce é utilizado principalmente para:', 20, 14),
(364, 'Qual característica diferencia bancos NoSQL dos relacionais?', 20, 14),
(365, 'Em MongoDB, qual comando é usado para consultar documentos?', 20, 14),
(376, 'Qual conceito da ISO 27001 trata da confidencialidade, integridade e disponibilidade?', 30, 13),
(236, 'Bancos de dados orientados a colunas são mais adequados para:', 30, 14),
(237, 'O conceito de Big Data está relacionado com:', 30, 14),
(238, 'Transações em bancos NoSQL têm como objetivo:', 30, 14),
(366, 'Qual técnica é usada para garantir consistência em sistemas distribuídos?', 30, 14),
(239, 'Qual alternativa representa corretamente um banco de dados chave-valor?', 30, 14),
(240, 'Ciência de Dados é uma área voltada para:', 30, 14),
(196, 'O que é um sistema embarcado?', 10, 15),
(197, 'Qual componente é utilizado para montagem de circuitos sem solda?', 10, 15),
(198, 'Em programas para microcontroladores, qual função é executada repetidamente?', 10, 15),
(199, 'Qual comando configura um pino como entrada ou saída?', 10, 15),
(200, 'LEDs são componentes utilizados para:', 10, 15),
(201, 'A função digitalWrite() é utilizada para:', 20, 15),
(202, 'A função analogRead() serve para:', 20, 15),
(203, 'Qual estrutura é utilizada para repetir instruções em programação?', 20, 15),
(204, 'O delay() é utilizado para:', 20, 15),
(205, 'O movimento maker está relacionado com:', 20, 15),
(206, 'A conversão Analógico-Digital permite:', 30, 15),
(207, 'A função millis() retorna:', 30, 15),
(208, 'Bibliotecas em sistemas embarcados são utilizadas para:', 30, 15),
(209, 'Qual alternativa representa corretamente uma característica da Internet das Coisas', 30, 15),
(210, 'O uso de timers e contadores em microcontroladores permite:', 30, 15),
(256, 'O que é uma API REST?', 10, 16),
(257, 'O Bluetooth é utilizado para:', 10, 16),
(258, 'Qual recurso do smartphone permite tirar fotos em aplicativos?', 10, 16),
(259, 'O GPS em aplicativos mobile é utilizado para:', 10, 16),
(260, 'O SMS em aplicativos mobile está relacionado com:', 10, 16),
(377, 'Qual recurso permite capturar imagens em aplicativos mobile?', 10, 16),
(378, 'Qual protocolo é mais usado para APIs REST?', 10, 16),
(261, 'O consumo de APIs REST permite que aplicativos:', 20, 16),
(262, 'A comunicação TCP full-duplex permite:', 20, 16),
(263, 'A autenticação em aplicativos mobile serve para:', 20, 16),
(379, 'Qual recurso permite identificar a posição geográfica do usuário?', 20, 16),
(380, 'Qual biblioteca é comumente usada para autenticação em apps mobile?', 20, 16),
(264, 'Sensores em smartphones podem ser usados para:', 20, 16),
(265, 'O empacotamento de aplicativos é o processo de:', 20, 16),
(266, 'A integração via Bluetooth com dispositivos embarcados permite:', 30, 16),
(267, 'APIs REST normalmente utilizam qual protocolo para comunicação?', 30, 16),
(381, 'Qual técnica permite comunicação contínua entre cliente e servidor em tempo real?', 30, 16),
(268, 'O uso de autenticação em aplicativos mobile ajuda a:', 30, 16),
(269, 'A utilização de mapas em aplicativos geralmente depende de:', 30, 16),
(270, 'O recurso de orientação em smartphones utiliza principalmente:', 30, 16),
(286, 'Recursos de orientação em smartphones utilizam principalmente:', 30, 16),
(287, 'O acesso a mapas em aplicativos geralmente depende de:', 30, 16),
(288, 'A distribuição de aplicativos mobile normalmente ocorre por meio de:', 30, 16),
(271, 'O que significa SPA em desenvolvimento web?', 10, 17),
(272, 'Em aplicações SPA, o roteamento é responsável por:', 10, 17),
(273, 'O que são componentes em frameworks web?', 10, 17),
(382, 'Qual conceito define aplicações que carregam conteúdo sem recarregar a página?', 10, 17),
(383, 'Qual elemento HTML é usado para formulários?', 10, 17),
(274, 'Qual recurso é usado para armazenar informações do usuário no navegador?', 10, 17),
(275, 'APIs REST são utilizadas para:', 10, 17),
(276, 'O gerenciamento de estados em aplicações SPA serve para:', 20, 17),
(277, 'O que é renderização de HTML?', 20, 17),
(384, 'Qual framework é usado para criar SPAs?', 20, 17),
(385, 'Qual técnica valida dados antes de enviar ao servidor?', 20, 17),
(278, 'Validação de formulários é utilizada para:', 20, 17),
(279, 'Um CMS é um sistema voltado para:', 20, 17),
(280, 'Sessões de usuário permitem:', 20, 17),
(281, 'O Hash de autenticação é utilizado para:', 30, 17),
(282, 'A autenticação em aplicações web serve para:', 30, 17),
(386, 'Qual política de segurança controla recursos entre diferentes origens?', 30, 17),
(283, 'A autorização em sistemas web define:', 30, 17),
(284, 'Testes automatizados têm como principal objetivo:', 30, 17),
(285, 'O acesso a dados via APIs REST geralmente utiliza:', 30, 17),
(304, 'Qual é o objetivo do teste de software?', 10, 18),
(305, 'O que significa legibilidade no código?', 10, 18),
(306, 'O que é reutilização de código?', 10, 18),
(307, 'A indentação no código serve para:', 10, 18),
(308, 'O que é UX (Experiência do Usuário)?', 10, 18),
(309, 'O que são testes funcionais?', 20, 18),
(310, 'Testes automatizados são executados:', 20, 18),
(311, 'O teste de usabilidade avalia:', 20, 18),
(312, 'O desenvolvimento orientado por testes (TDD) consiste em:', 20, 18),
(313, 'A programação em par acontece quando:', 20, 18),
(314, 'O objetivo da refatoração é:', 30, 18),
(315, 'Testes de integração verificam:', 30, 18),
(316, 'Testes não funcionais analisam aspectos como:', 30, 18),
(317, 'O modelo CMMI está relacionado com:', 30, 18),
(318, 'A validação em testes de software busca garantir que:', 30, 18),
(1, 'O que significa “manual técnico” em inglês?', 10, 20),
(2, 'Qual é a tradução correta de “e-mail comercial”?', 10, 20),
(3, '“Glossário técnico” em inglês é:', 10, 20),
(319, 'O que significa "meeting" em inglês?', 10, 20),
(320, 'Qual é a tradução correta de "technical report"?', 10, 20),
(4, 'O que significa “customer service”?', 10, 20),
(5, '“Carta comercial” em inglês é:', 10, 20),
(6, 'O que significa “listening” no contexto de inglês instrumental?', 20, 20),
(7, 'O que significa “speaking” no ambiente profissional?', 20, 20),
(8, 'O que significa “reading” em inglês instrumental?', 20, 20),
(9, 'O que significa “writing” em inglês instrumental?', 20, 20),
(321, 'O que significa "deadline" em contexto profissional?', 20, 20),
(322, 'O que significa "job interview"?', 20, 20),
(10, 'O que significa “grammar focus”?', 20, 20),
(11, 'O que significa “technical terminology”?', 30, 20),
(12, 'O que significa “administrative correspondence”?', 30, 20),
(13, 'O que significa “scientific article”?', 30, 20),
(14, 'O que significa “business communication”?', 30, 20),
(323, 'O que significa "executive summary"?', 30, 20),
(15, 'O que significa “technical documentation”?', 30, 20),
(16, 'O que é ética?', 10, 21),
(17, 'O que é cidadania?', 10, 21),
(18, 'O que é moral?', 10, 21),
(19, 'O que é respeito no ambiente de trabalho?', 10, 21),
(20, 'O que é responsabilidade social?', 10, 21),
(324, 'O que é empatia?', 10, 21),
(21, 'O que é ética profissional?', 20, 21),
(22, 'O que é Código de Defesa do Consumidor?', 20, 21),
(23, 'O que é legislação ambiental?', 20, 21),
(24, 'O que é Código de Ética de TI?', 20, 21),
(325, 'O que significa responsabilidade ambiental?', 20, 21),
(25, 'O que é inclusão social?', 20, 21),
(26, 'O que é a Lei da Transparência (Lei Complementar 131/2009)?', 30, 21),
(27, 'O que é a Lei de Acesso à Informação (Lei 12.527/2011)?', 30, 21),
(326, 'O que é compliance corporativo?', 30, 21),
(28, 'O que é a LGPD (Lei 13.709/2018)?', 30, 21),
(29, 'O que é responsabilidade corporativa?', 30, 21),
(30, 'O que é governança corporativa?', 30, 21),
(76, 'Qual programa é usado para edição de textos?', 10, 22),
(77, 'Qual programa é usado para planilhas eletrônicas?', 10, 22),
(78, 'Qual programa é usado para apresentações?', 10, 22),
(79, 'Qual recurso do Word insere numeração automática em listas?', 10, 22),
(336, 'Qual programa é usado para gerenciar e-mails?', 10, 22),
(80, 'Qual recurso do Excel permite somar valores rapidamente?', 10, 22),
(81, 'Qual recurso do Word permite criar cartas personalizadas para vários', 20, 22),
(337, 'Qual recurso do Excel permite criar gráficos automaticamente?', 20, 22),
(82, 'Qual recurso do Excel permite aplicar regras visuais a células?', 20, 22),
(83, 'Qual recurso do PowerPoint adiciona movimento aos elementos do', 20, 22),
(84, 'Qual recurso do Word gera automaticamente índice de capítulos?', 20, 22),
(85, 'Qual recurso do Excel permite organizar dados em ordem crescente ou', 20, 22),
(86, 'Qual função do Excel retorna um valor de uma tabela com base em uma', 30, 22),
(338, 'Qual recurso do PowerPoint permite sincronizar apresentações com áudio narrado?', 30, 22),
(87, 'Qual recurso do Word insere citações e gera bibliografia', 30, 22),
(88, 'Qual recurso do PowerPoint permite criar botões interativos nos slides?', 30, 22),
(89, 'Qual recurso do Excel permite criar relatórios dinâmicos a partir de', 30, 22),
(90, 'Qual recurso colaborativo permite editar documentos em tempo real na', 30, 22),
(289, 'O que é linguagem formal?', 10, 23),
(290, 'O que é um currículo?', 10, 23),
(291, 'Qual documento é usado para comunicação interna em empresas?', 10, 23),
(292, 'O que significa coesão textual?', 10, 23),
(387, 'O que é coerência em um texto técnico?', 10, 23),
(388, 'Qual gênero textual é usado para comunicação interna rápida?', 10, 23),
(293, 'O que é um relatório técnico?', 10, 23),
(294, 'O objetivo da leitura instrumental é:', 20, 23),
(389, 'Qual indicador extralinguístico considera o público-alvo do texto?', 20, 23),
(390, 'Qual documento apresenta critérios técnicos de um projeto?', 20, 23),
(295, 'O que são indicadores linguísticos?', 20, 23),
(296, 'Qual é a função das palavras-chave em um texto técnico?', 20, 23),
(297, 'O que é coerência textual?', 20, 23),
(298, 'A carta-currículo tem como finalidade:', 20, 23),
(391, 'Qual técnica de leitura foca na confiabilidade das fontes?', 30, 23),
(299, 'O que caracteriza um texto técnico-científico?', 30, 23),
(300, 'As referências bibliográficas servem para:', 30, 23),
(301, 'O glossário técnico é utilizado para:', 30, 23),
(302, 'Na apresentação oral técnico-científica, o planejamento é importante para:', 30, 23),
(303, 'A análise da confiabilidade das fontes busca verificar:', 30, 23),
(392, 'Qual prática melhora a legibilidade do código?', 10, 24),
(393, 'Qual conceito busca melhorar a experiência do usuário?', 10, 24),
(394, 'Qual tipo de teste verifica se o sistema atende às necessidades do usuário?', 20, 24),
(395, 'Qual prática de programação incentiva colaboração entre dois desenvolvedores?', 20, 24),
(396, 'Qual modelo de qualidade de software é brasileiro?', 30, 24);


INSERT INTO alternativa (id_questao, perguntas, correta) VALUES
(1, 'User file', 0),
(1, 'Technical manual', 1),
(1, 'Data sheet', 0),
(1, 'Work paper', 0),
(2, 'Company mail', 0),
(2, 'Office text', 0),
(2, 'Business e-mail', 1),
(2, 'Work letter', 0),
(3, 'Technical notes', 0),
(3, 'Technical dictionary', 0),
(3, 'Technical glossary', 1),
(3, 'Technical list', 0),
(4, 'Rede social', 0),
(4, 'Atendimento ao cliente', 1),
(4, 'Sistema operacional', 0),
(4, 'Banco de dados', 0),
(5, 'Work card', 0),
(5, 'Company note', 0),
(5, 'Office paper', 0),
(5, 'Business letter', 1),
(6, 'Produção de glossários', 0),
(6, 'Escrita técnica', 0),
(6, 'Compreensão auditiva', 1),
(6, 'Leitura de textos', 0),
(7, 'Produção de glossários', 0),
(7, 'Expressão oral', 1),
(7, 'Leitura de textos', 0),
(7, 'Escrita técnica', 0),
(8, 'Produção de textos', 0),
(8, 'Vocabulário técnico', 0),
(8, 'Estratégias de leitura e interpretação', 1),
(8, 'Expressão oral', 0),
(9, 'Produção de textos técnicos', 1),
(9, 'Vocabulário técnico', 0),
(9, 'Compreensão auditiva', 0),
(9, 'Expressão oral', 0),
(10, 'Produção de textos', 0),
(10, 'Expressão oral', 0),
(10, 'Vocabulário técnico', 0),
(10, 'Compreensão e uso dos aspectos linguísticos', 1),
(11, 'Vocabulário coloquial', 0),
(11, 'Terminologia técnico-científica', 1),
(11, 'Vocabulário informal', 0),
(11, 'Vocabulário literário', 0),
(12, 'Glossário técnico', 0),
(12, 'Carta pessoal', 0),
(12, 'Correspondência administrativa', 1),
(12, 'Texto literário', 0),
(13, 'Carta comercial', 0),
(13, 'Manual de instruções', 0),
(13, 'Artigo técnico-científico', 1),
(13, 'Folheto de divulgação', 0),
(14, 'Comunicação artística', 0),
(14, 'Comunicação pessoal', 0),
(14, 'Comunicação empresarial', 1),
(14, 'Comunicação literária', 0),
(15, 'Texto literário', 0),
(15, 'Glossário informal', 0),
(15, 'Carta pessoal', 0),
(15, 'Documentação técnica', 1),
(16, 'Conjunto de valores e princípios', 1),
(16, 'Banco de dados', 0),
(16, 'Hardware', 0),
(16, 'Software', 0),
(17, 'Banco de dados', 0),
(17, 'Exercício de direitos e deveres', 1),
(17, 'Hardware', 0),
(17, 'Software', 0),
(18, 'Banco de dados', 0),
(18, 'Hardware', 0),
(18, 'Conjunto de costumes e regras sociais', 1),
(18, 'Software', 0),
(19, 'Criar tabelas', 0),
(19, 'Executar programas', 0),
(19, 'Compilar código', 0),
(19, 'Reconhecimento do valor do outro', 1),
(20, 'Compromisso da empresa com a sociedade', 1),
(20, 'Criar variáveis', 0),
(20, 'Compilar programas', 0),
(20, 'Usar IDE', 0),
(21, 'Banco de dados', 0),
(21, 'Conjunto de regras de conduta no trabalho', 1),
(21, 'Hardware', 0),
(21, 'Software', 0),
(22, 'Manual técnico', 0),
(22, 'Banco de dados', 0),
(22, 'Conjunto de normas que protegem os direitos do consumidor', 1),
(22, 'Hardware', 0),
(23, 'Normas que regulam o uso sustentável dos recursos naturais', 1),
(23, 'Manual técnico', 0),
(23, 'Banco de dados', 0),
(23, 'Hardware', 0),
(24, 'Manual técnico', 0),
(24, 'Banco de dados', 0),
(24, 'Hardware', 0),
(24, 'Normas de conduta para profissionais de tecnologia', 1),
(25, 'Garantia de participação de todos na sociedade', 1),
(25, 'Banco de dados', 0),
(25, 'Hardware', 0),
(25, 'Software', 0),
(26, 'Lei que regula direitos autorais', 0),
(26, 'Lei que obriga União, estados e municípios a divulgar seus gastos em', 1),
(26, 'Lei que cria o Código de Defesa do Consumidor', 0),
(26, 'Lei que regula patentes', 0),
(27, 'Lei que garante acesso às informações públicas', 1),
(27, 'Lei que regula direitos autorais', 0),
(27, 'Lei que cria o Código de Defesa do Consumidor', 0),
(27, 'Lei que regula patentes', 0),
(28, 'Lei de Direitos Autorais', 0),
(28, 'Lei da Transparência', 0),
(28, 'Lei Geral de Proteção de Dados Pessoais', 1),
(28, 'Lei de Acesso à Informação', 0),
(29, 'Criar variáveis', 0),
(29, 'Compilar programas', 0),
(29, 'Usar IDE', 0),
(29, 'Compromisso da empresa com sociedade e meio ambiente', 1),
(30, 'Conjunto de práticas para gestão responsável e transparente', 1),
(30, 'Banco de dados', 0),
(30, 'Hardware', 0),
(30, 'Software', 0),
(31, 'Imagem formada por pixels', 1),
(31, 'Imagem formada por vetores', 0),
(31, 'Texto digital', 0),
(31, 'Som digital', 0),
(32, 'SVG', 0),
(32, 'JPG', 1),
(32, 'TXT', 0),
(32, 'DOC', 0),
(33, 'Imagem formada por pixels', 0),
(33, 'Texto digital', 0),
(33, 'Imagem formada por linhas e curvas matemáticas', 1),
(33, 'Som digital', 0),
(34, 'JPG', 0),
(34, 'PNG', 0),
(34, 'DOC', 0),
(34, 'SVG', 1),
(35, 'Modelo de cores usado para impressão', 1),
(35, 'Modelo de cores usado em telas', 0),
(35, 'Código de programação', 0),
(35, 'Banco de dados', 0),
(36, 'Modelo de cores usado em telas', 1),
(36, 'Modelo de cores usado para impressão', 0),
(36, 'Código de programação', 0),
(36, 'Banco de dados', 0),
(37, 'Criação de banco de dados', 0),
(37, 'Criação de modelos visuais iniciais de aplicativos e sites', 1),
(37, 'Criação de hardware', 0),
(37, 'Criação de textos', 0),
(38, 'Banco de dados', 0),
(38, 'Hardware', 0),
(38, 'Estilo e aparência das letras', 1),
(38, 'Software', 0),
(39, 'Modelo de cores', 0),
(39, 'Linguagem de programação', 0),
(39, 'Banco de dados', 0),
(39, 'Conjunto de princípios de percepção visual', 1),
(40, 'Capacidade de deixar áreas sem cor visíveis', 1),
(40, 'Capacidade de aumentar resolução', 0),
(40, 'Capacidade de criar vetores', 0),
(40, 'Capacidade de criar texto', 0),
(41, 'Código usado para representar cores em sistemas digitais', 1),
(41, 'Código usado para representar texto', 0),
(41, 'Código usado para representar sons', 0),
(41, 'Código usado para representar vetores', 0),
(42, 'Banco de dados', 0),
(42, 'Esboço estrutural de uma interface', 1),
(42, 'Hardware', 0),
(42, 'Software', 0),
(43, 'Texto digital', 0),
(43, 'Som digital', 0),
(43, 'Símbolo gráfico simples que representa uma ideia ou objeto', 1),
(43, 'Banco de dados', 0),
(44, 'Banco de dados relacional', 0),
(44, 'Banco de sons', 0),
(44, 'Banco de textos', 0),
(44, 'Repositório de imagens para uso em projetos', 1),
(45, 'Protótipo detalhado próximo ao produto final', 1),
(45, 'Protótipo simples em papel', 0),
(45, 'Banco de dados', 0),
(45, 'Hardware', 0),
(46, 'Criar parágrafo', 1),
(46, 'Criar tabela', 0),
(46, 'Criar imagem', 0),
(46, 'Criar link', 0),
(47, 'Criar parágrafo', 0),
(47, 'Inserir imagem', 1),
(47, 'Criar tabela', 0),
(47, 'Criar link', 0),
(48, 'Criar tabela', 0),
(48, 'Criar imagem', 0),
(48, 'Criar link', 1),
(48, 'Criar parágrafo', 0),
(49, 'Definir tamanho da fonte', 0),
(49, 'Definir margem', 0),
(49, 'Definir borda', 0),
(49, 'Definir cor do texto', 1),
(50, 'Definir cor de fundo', 1),
(50, 'Definir cor do texto', 0),
(50, 'Definir tamanho da fonte', 0),
(50, 'Definir borda', 0),
(51, 'Criar formulário', 1),
(51, 'Criar tabela', 0),
(51, 'Criar imagem', 0),
(51, 'Criar link', 0),
(52, 'Criar formulário', 0),
(52, 'Criar tabela', 1),
(52, 'Criar imagem', 0),
(52, 'Criar link', 0),
(53, 'Criar variável', 0),
(53, 'Executar função', 0),
(53, 'Selecionar elemento pelo ID', 1),
(53, 'Criar tabela', 0),
(54, 'Tomar decisões no código', 1),
(54, 'Criar variáveis', 0),
(54, 'Criar tabelas', 0),
(54, 'Inserir imagens', 0),
(55, 'Criar tabelas', 0),
(55, 'Criar links', 0),
(55, 'Criar imagens', 0),
(55, 'Definir margens, bordas, padding e conteúdo', 1),
(56, 'Organizar elementos em layouts flexíveis', 1),
(56, 'Criar tabelas', 0),
(56, 'Criar links', 0),
(56, 'Criar imagens', 0),
(57, 'Criar tabelas', 0),
(57, 'Organizar elementos em grades bidimensionais', 1),
(57, 'Criar links', 0),
(57, 'Criar imagens', 0),
(58, 'Estrutura para criar variáveis', 0),
(58, 'Estrutura para criar tabelas', 0),
(58, 'Estrutura para lidar com programação assíncrona', 1),
(58, 'Estrutura para criar links', 0),
(59, 'Criar tabelas', 0),
(59, 'Criar links', 0),
(59, 'Criar imagens', 0),
(59, 'Formato para troca de dados', 1),
(60, 'Publicar sites estáticos', 1),
(60, 'Criar tabelas', 0),
(60, 'Criar links', 0),
(60, 'Criar imagens', 0),
(61, 'Parte física do computador', 1),
(61, 'Programas de computador', 0),
(61, 'Banco de dados', 0),
(61, 'Rede', 0),
(62, 'Parte física', 0),
(62, 'Programas e sistemas', 1),
(62, 'Cabos e periféricos', 0),
(62, 'Internet', 0),
(63, 'Excel', 0),
(63, 'Chrome', 0),
(63, 'Windows', 1),
(63, 'Word', 0),
(64, 'Memória permanente', 0),
(64, 'Disco rígido', 0),
(64, 'Processador', 0),
(64, 'Memória temporária de acesso rápido', 1),
(65, 'Teclado', 1),
(65, 'Monitor', 0),
(65, 'Impressora', 0),
(65, 'Caixa de som', 0),
(66, 'Forma de representar informações usando 0 e 1', 1),
(66, 'Forma de representar informações usando letras', 0),
(66, 'Forma de representar informações usando imagens', 0),
(66, 'Forma de representar informações usando sons', 0),
(67, 'Software pago', 0),
(67, 'Software que pode ser usado, modificado e distribuído livremente', 1),
(67, 'Software de rede', 0),
(67, 'Software proprietário', 0),
(68, 'Backup de arquivos', 0),
(68, 'Criação de tabelas', 0),
(68, 'Uso de máquinas virtuais para simular sistemas', 1),
(68, 'Instalação de programas', 0),
(69, 'Rede mundial', 0),
(69, 'Rede sem fio global', 0),
(69, 'Rede de servidores', 0),
(69, 'Rede de computadores em pequena área', 1),
(70, 'Armazenamento e processamento de dados pela internet', 1),
(70, 'Disco rígido externo', 0),
(70, 'Memória RAM', 0),
(70, 'Processador', 0),
(71, 'dir', 1),
(71, 'ls', 0),
(71, 'cd', 0),
(71, 'pwd', 0),
(72, 'dir', 0),
(72, 'ls', 1),
(72, 'cd', 0),
(72, 'pwd', 0),
(73, 'ls', 0),
(73, 'dir', 0),
(73, 'cd', 1),
(73, 'pwd', 0),
(74, 'ls', 0),
(74, 'cd', 0),
(74, 'dir', 0),
(74, 'pwd', 1),
(75, 'Conexão de objetos físicos à internet para troca de dados', 1),
(75, 'Banco de dados relacional', 0),
(75, 'Disco rígido externo', 0),
(75, 'Memória RAM', 0),
(76, 'Word', 1),
(76, 'Excel', 0),
(76, 'PowerPoint', 0),
(76, 'Access', 0),
(77, 'Word', 0),
(77, 'Excel', 1),
(77, 'PowerPoint', 0),
(77, 'Outlook', 0),
(78, 'Word', 0),
(78, 'Excel', 0),
(78, 'PowerPoint', 1),
(78, 'Access', 0),
(79, 'Mala direta', 0),
(79, 'Cabeçalho', 0),
(79, 'Sumário', 0),
(79, 'Marcadores e numeração', 1),
(80, 'Função SOMA', 1),
(80, 'Função MÉDIA', 0),
(80, 'Função SE', 0),
(80, 'Função PROCV', 0),
(81, 'Mala direta', 1),
(81, 'Cabeçalho', 0),
(81, 'Rodapé', 0),
(81, 'Sumário', 0),
(82, 'Função SE', 0),
(82, 'Formatação condicional', 1),
(82, 'Filtro', 0),
(82, 'Gráfico', 0),
(83, 'Layout', 0),
(83, 'Hiperlink', 0),
(83, 'Animações', 1),
(83, 'Cabeçalho', 0),
(84, 'Mala direta', 0),
(84, 'Rodapé', 0),
(84, 'Comentários', 0),
(84, 'Sumário', 1),
(85, 'Classificação', 1),
(85, 'Filtro', 0),
(85, 'Gráfico', 0),
(85, 'Validação', 0),
(86, 'PROCV', 1),
(86, 'SOMA', 0),
(86, 'MÉDIA', 0),
(86, 'SE', 0),
(87, 'Mala direta', 0),
(87, 'Referências', 1),
(87, 'Sumário', 0),
(87, 'Comentários', 0),
(88, 'Layout', 0),
(88, 'Cabeçalho', 0),
(88, 'Hiperlinks e botões de ação', 1),
(88, 'Rodapé', 0),
(89, 'Filtro', 0),
(89, 'Gráfico', 0),
(89, 'Classificação', 0),
(89, 'Tabela dinâmica', 1),
(90, 'Aplicativos online como Google Docs e Office 365', 1),
(90, 'Word offline', 0),
(90, 'Excel offline', 0),
(90, 'PowerPoint offline', 0),
(91, 'Conjunto organizado de informações', 1),
(91, 'Programa de edição de texto', 0),
(91, 'Hardware', 0),
(91, 'Rede', 0),
(92, 'Simple Query Language', 0),
(92, 'Structured Query Language', 1),
(92, 'System Query Language', 0),
(92, 'Standard Quick Language', 0),
(93, 'Executar programas', 0),
(93, 'Criar variáveis', 0),
(93, 'Organizar dados em linhas e colunas', 1),
(93, 'Depurar erros', 0),
(94, 'Um compilador', 0),
(94, 'Uma constante', 0),
(94, 'Uma linguagem', 0),
(94, 'Identificador único de registros', 1),
(95, 'MySQL', 1),
(95, 'Python', 0),
(95, 'Excel', 0),
(95, 'HTML', 0),
(96, 'DELETE remove dados, DROP remove tabela', 1),
(96, 'Ambos removem tabelas', 0),
(96, 'Ambos removem dados', 0),
(96, 'Não há diferença', 0),
(97, 'Criação de variáveis', 0),
(97, 'Conexão entre dados de diferentes tabelas', 1),
(97, 'Execução de programas', 0),
(97, 'Depuração', 0),
(98, 'Apagar registros', 0),
(98, 'Criar tabelas', 0),
(98, 'Consultar dados', 1),
(98, 'Compilar código', 0),
(99, 'Criar variáveis', 0),
(99, 'Executar programas', 0),
(99, 'Depurar erros', 0),
(99, 'Processo de estruturar dados e relações', 1),
(100, 'Campo que referencia chave primária de outra tabela', 1),
(100, 'Um compilador', 0),
(100, 'Uma constante', 0),
(100, 'Uma linguagem', 0),
(101, 'Relacionais usam tabelas, não relacionais usam documentos ou', 1),
(101, 'Ambos usam tabelas', 0),
(101, 'Ambos usam grafos', 0),
(101, 'Não há diferença', 0),
(102, 'Criar variáveis', 0),
(102, 'Processo de organizar dados para evitar redundância', 1),
(102, 'Executar programas', 0),
(102, 'Depurar erros', 0),
(103, 'Cria variáveis', 0),
(103, 'Apaga registros', 0),
(103, 'Combina dados de duas ou mais tabelas', 1),
(103, 'Compila código', 0),
(104, 'Criar variáveis', 0),
(104, 'Executar programas', 0),
(104, 'Depurar erros', 0),
(104, 'Garantir consistência entre tabelas relacionadas', 1),
(105, 'Definir entidades, atributos, relacionamentos e restrições', 1),
(105, 'Criar variáveis', 0),
(105, 'Compilar programas', 0),
(105, 'Usar IDE', 0),
(106, 'Conjunto de instruções para resolver um problema', 1),
(106, 'Banco de dados', 0),
(106, 'Hardware', 0),
(106, 'Software', 0),
(107, 'Valor fixo', 0),
(107, 'Espaço na memória que pode armazenar valores', 1),
(107, 'Banco de dados', 0),
(107, 'Hardware', 0),
(108, 'Valor que muda sempre', 0),
(108, 'Banco de dados', 0),
(108, 'Valor que não pode ser alterado durante a execução', 1),
(108, 'Hardware', 0),
(109, 'Banco de dados', 0),
(109, 'Hardware', 0),
(109, 'Software', 0),
(109, 'Ambiente de desenvolvimento integrado', 1),
(110, 'Processo de encontrar e corrigir erros', 1),
(110, 'Criar variáveis', 0),
(110, 'Compilar programas', 0),
(110, 'Usar banco de dados', 0),
(111, 'Tomar decisões no código', 1),
(111, 'Criar variáveis', 0),
(111, 'Criar tabelas', 0),
(111, 'Inserir imagens', 0),
(112, 'Estrutura que cria variáveis', 0),
(112, 'Estrutura que executa um bloco de código várias vezes', 1),
(112, 'Estrutura que compila programas', 0),
(112, 'Estrutura que cria tabelas', 0),
(113, 'Criação de variáveis', 0),
(113, 'Execução automática', 0),
(113, 'Simulação manual da execução de um algoritmo', 1),
(113, 'Compilação', 0),
(114, 'Criação de variáveis', 0),
(114, 'Compilação', 0),
(114, 'Depuração', 0),
(114, 'Divisão do programa em funções e procedimentos', 1),
(115, 'Função que chama a si mesma', 1),
(115, 'Função que cria variáveis', 0),
(115, 'Função que compila programas', 0),
(115, 'Função que cria tabelas', 0),
(116, 'Compilador traduz todo o código antes da execução, interpretador', 1),
(116, 'Ambos fazem a mesma coisa', 0),
(116, 'Interpretador é mais rápido', 0),
(116, 'Compilador não existe', 0),
(117, 'Banco de dados', 0),
(117, 'Estrutura que armazena a sequência de chamadas de funções', 1),
(117, 'Hardware', 0),
(117, 'Software', 0),
(118, 'Criação de variáveis', 0),
(118, 'Compilação', 0),
(118, 'Mecanismo para lidar com erros durante a execução', 1),
(118, 'Depuração', 0),
(119, 'Estrutura que armazena apenas um valor', 0),
(119, 'Banco de dados', 0),
(119, 'Hardware', 0),
(119, 'Estrutura que armazena vários valores do mesmo tipo em sequência', 1),
(120, 'Estrutura bidimensional que armazena valores em linhas e colunas', 1),
(120, 'Estrutura unidimensional', 0),
(120, 'Banco de dados', 0),
(120, 'Hardware', 0),
(121, 'Define regras de funcionamento do sistema', 1),
(121, 'Define o horário da empresa', 0),
(121, 'Define os custos do projeto', 0),
(121, 'Define a quantidade de funcionários', 0),
(122, 'UML', 0),
(122, 'Scrum', 1),
(122, 'Ferramenta CASE', 0),
(122, 'Modelo relacional', 0),
(123, 'Calculadora', 0),
(123, 'Word', 0),
(123, 'Trello', 1),
(123, 'Paint', 0),
(124, 'Usuário final', 0),
(124, 'Desenvolvedor', 0),
(124, 'Product Owner', 0),
(124, 'Scrum Master', 1),
(125, 'O valor do software', 0),
(125, 'O tempo de garantia do computador', 0),
(125, 'As etapas de desenvolvimento do sistema', 1),
(125, 'O número de usuários', 0),
(126, 'Scrum, Kanban e UML', 0),
(126, 'Funcionais, não funcionais e regras de negócio', 1),
(126, 'Sprint, backlog e incremento', 0),
(126, 'Cascata, Scrum e XP', 0),
(127, 'Uma lista de funcionalidades do produto', 1),
(127, 'Um relatório financeiro', 0),
(127, 'Um diagrama UML', 0),
(127, 'Uma linguagem de programação', 0),
(128, 'Criar jogos', 0),
(128, 'Desenvolver bancos físicos', 0),
(128, 'Modelar sistemas orientados a objetos', 1),
(128, 'Fazer manutenção de computadores', 0),
(129, 'Formatar computadores', 0),
(129, 'Criar planilhas financeiras', 0),
(129, 'Trocar ferramentas CASE', 0),
(129, 'Testar rapidamente ideias e soluções', 1),
(130, 'Desenvolvimento sem etapas', 0),
(130, 'Ausência de documentação', 0),
(130, 'Etapas realizadas de forma sequencial', 1),
(130, 'Entregas diárias obrigatórias', 0),
(131, 'Revisão da Sprint', 1),
(131, 'Reunião diária', 0),
(131, 'Planejamento da Sprint', 0),
(131, 'Retrospectiva da Sprint', 0),
(132, 'Controlar redes de internet', 0),
(132, 'Auxiliar na análise e desenvolvimento de sistemas', 1),
(132, 'Fazer manutenção física de computadores', 0),
(132, 'Substituir programadores', 0),
(133, 'Processos acima de indivíduos', 0),
(133, 'Contratos acima da colaboração', 0),
(133, 'Indivíduos e interações acima de processos e ferramentas', 1),
(133, 'Documentação acima de software funcionando', 0),
(134, 'Criar bancos de dados', 0),
(134, 'Eliminar programadores', 0),
(134, 'Substituir o Scrum', 0),
(134, 'Visualizar e controlar o fluxo de trabalho', 1),
(135, 'Configurar computadores', 0),
(135, 'Gerenciar e priorizar o Backlog do Produto', 1),
(135, 'Fazer manutenção da rede', 0),
(135, 'Desenvolver sozinho o sistema', 0),
(136, 'Um tipo de banco de dados', 0),
(136, 'Uma instância de uma classe', 1),
(136, 'Um sistema operacional', 0),
(136, 'Um compilador', 0),
(137, 'Método', 0),
(137, 'Interface', 0),
(137, 'Atributo', 1),
(137, 'Namespace', 0),
(138, 'Organizar a estrutura do sistema', 1),
(138, 'Criar redes de computadores', 0),
(138, 'Desenvolver hardware', 0),
(138, 'Fazer manutenção física', 0),
(139, 'Create', 0),
(139, 'Read', 0),
(139, 'Update', 0),
(139, 'Delete', 1),
(140, 'Caixa de texto', 0),
(140, 'Painel', 0),
(140, 'Botão de rádio', 1),
(140, 'Aba', 0),
(141, 'Aumentar o tamanho do programa', 0),
(141, 'Proteger e controlar o acesso aos dados', 1),
(141, 'Excluir métodos automaticamente', 0),
(141, 'Criar bancos de dados relacionais', 0),
(142, 'Utilize características de outra classe', 1),
(142, 'Apague atributos automaticamente', 0),
(142, 'Crie apenas interfaces gráficas', 0),
(142, 'Trabalhe sem métodos', 0),
(143, 'Criar formulários gráficos', 0),
(143, 'Gerenciar acesso aos dados do banco', 1),
(143, 'Desenvolver jogos', 0),
(143, 'Fazer conexões de internet', 0),
(144, 'Criação automática de tabelas', 0),
(144, 'Organização de pastas', 0),
(144, 'Prevenção de SQL Injection', 1),
(144, 'Criação de botões gráficos', 0),
(145, 'Um método tenha diferentes comportamentos', 1),
(145, 'Um banco de dados seja excluído', 0),
(145, 'Um formulário fique invisível', 0),
(145, 'Um sistema funcione sem classes', 0),
(146, 'Um método é apagado automaticamente', 0),
(146, 'Dois métodos possuem o mesmo nome com parâmetros diferentes', 1),
(146, 'Uma classe não possui atributos', 0),
(146, 'O sistema utiliza mais de um banco de dados', 0),
(147, 'Não poderem ser herdadas', 0),
(147, 'Não utilizarem métodos', 0),
(147, 'Servirem como modelo para outras classes', 1),
(147, 'Funcionarem apenas em interfaces gráficas', 0),
(148, 'Misturar interface e banco de dados no mesmo código', 0),
(148, 'Eliminar o uso de classes', 0),
(148, 'Impedir reutilização de código', 0),
(148, 'Separar responsabilidades da aplicação', 1),
(149, 'Organizar classes e evitar conflitos de nomes', 1),
(149, 'Criar botões automaticamente', 0),
(149, 'Substituir bancos de dados', 0),
(149, 'Excluir métodos duplicados', 0),
(150, 'Um método da classe filha redefine o método da classe pai', 1),
(150, 'Um método é executado duas vezes', 0),
(150, 'Uma interface gráfica é recriada', 0),
(150, 'Um atributo é removido da memória', 0),
(151, 'Desenvolver e planejar um projeto na área profissional', 1),
(151, 'Apenas estudar matemática', 0),
(151, 'Fazer manutenção de computadores', 0),
(151, 'Criar redes de internet', 0),
(152, 'Questionário', 1),
(152, 'Compilador', 0),
(152, 'Firewall', 0),
(152, 'Driver', 0),
(153, 'Organizar as etapas e prazos do projeto', 1),
(153, 'Excluir informações do projeto', 0),
(153, 'Criar bancos de dados', 0),
(153, 'Desenvolver hardware', 0),
(154, 'Quem?', 0),
(154, 'Onde?', 0),
(154, 'Por quê?', 1),
(154, 'Quando?', 0),
(155, 'Questionário', 1),
(155, 'Antivírus', 0),
(155, 'Linguagem de programação', 0),
(155, 'Sistema operacional', 0),
(156, 'Documentação indireta', 1),
(156, 'Pesquisa prática', 0),
(156, 'Desenvolvimento mobile', 0),
(156, 'Programação orientada a objetos', 0),
(157, 'Popularidade em redes sociais', 0),
(157, 'Viabilidade', 1),
(157, 'Quantidade de computadores disponíveis', 0),
(157, 'Tipo de internet utilizada', 0),
(158, 'O custo do sistema', 0),
(158, 'As linguagens de programação utilizadas', 0),
(158, 'O que se pretende alcançar com o trabalho', 1),
(158, 'Apenas o cronograma do projeto', 0),
(159, 'A definição do problema a ser estudado', 1),
(159, 'A criação de jogos eletrônicos', 0),
(159, 'A manutenção de hardware', 0),
(159, 'A exclusão de hipóteses', 0),
(160, 'Formatar computadores', 0),
(160, 'Organizar informações de pesquisas e obras', 1),
(160, 'Criar aplicativos mobile', 0),
(160, 'Excluir documentos do projeto', 0),
(161, 'Definir possíveis respostas para o problema estudado', 1),
(161, 'Excluir dados da pesquisa', 0),
(161, 'Criar bancos de dados automáticos', 0),
(161, 'Impedir entrevistas de campo', 0),
(162, 'Encontrar demandas não atendidas plenamente', 1),
(162, 'Desenvolver apenas sistemas antigos', 0),
(162, 'Eliminar novas tecnologias', 0),
(162, 'Substituir pesquisas bibliográficas', 0),
(163, 'Escolher o tema do TCC', 1),
(163, 'Criar linguagens de programação', 0),
(163, 'Desenvolver peças de hardware', 0),
(163, 'Organizar servidores de rede', 0),
(164, 'Pesquisa bibliográfica', 0),
(164, 'Pesquisa documental', 0),
(164, 'Entrevista', 1),
(164, 'Fichamento técnico', 0),
(165, 'Permite desenvolver soluções e modelos de negócio inovadores', 1),
(165, 'Elimina a necessidade de planejamento', 0),
(165, 'Substitui a pesquisa científica', 0),
(165, 'Impede a criação de softwares', 0),
(166, 'Sistema operacional de computadores', 0),
(166, 'Planejamento das tarefas e prazos de um projeto', 1),
(166, 'Banco de dados relacional', 0),
(166, 'Linguagem de programação', 0),
(167, 'Criar aplicativos mobile', 0),
(167, 'Configurar redes de computadores', 0),
(167, 'Registrar informações e resultados de um projeto', 1),
(167, 'Editar imagens digitais', 0),
(168, 'Programa de edição de textos', 0),
(168, 'Banco de dados em nuvem', 0),
(168, 'Sistema de autenticação', 0),
(168, 'Representação gráfica de etapas de um processo', 1),
(169, 'Fontes e estudos utilizados como base do trabalho', 1),
(169, 'Equipamentos de hardware', 0),
(169, 'Configurações de rede', 0),
(169, 'Arquivos de instalação', 0),
(170, 'Tipo de linguagem de programação', 0),
(170, 'Conjunto de métodos e procedimentos utilizados', 1),
(170, 'Sistema de armazenamento físico', 0),
(170, 'Estrutura de redes sociais', 0),
(171, 'Organizar informações coletadas em tabelas ou gráficos', 1),
(171, 'Criar sistemas operacionais', 0),
(171, 'Desenvolver hardware', 0),
(171, 'Configurar impressoras', 0),
(172, 'Criar bancos de dados físicos', 0),
(172, 'Melhorar velocidade da internet', 0),
(172, 'Interpretar e explicar informações obtidas na pesquisa', 1),
(172, 'Desenvolver jogos digitais', 0),
(173, 'Configurar sistemas embarcados', 0),
(173, 'Criar layouts de sites', 0),
(173, 'Editar vídeos digitais', 0),
(173, 'Definir materiais, custos e necessidades do projeto', 1),
(174, 'Facilitar a visualização e interpretação de dados', 1),
(174, 'Criar autenticação de usuários', 0),
(174, 'Configurar servidores HTTP', 0),
(174, 'Desenvolver drivers de hardware', 0),
(175, 'Criar componentes eletrônicos', 0),
(175, 'Organizar tarefas, equipes e prazos', 1),
(175, 'Desenvolver processadores', 0),
(175, 'Configurar roteadores físicos', 0),
(176, 'Padronizar a apresentação e organização do conteúdo', 1),
(176, 'Melhorar desempenho do hardware', 0),
(176, 'Configurar aplicativos mobile', 0),
(176, 'Criar bancos NoSQL', 0),
(177, 'Desenvolver sistemas operacionais', 0),
(177, 'Classificar e organizar informações coletadas', 1),
(177, 'Configurar sensores digitais', 0),
(177, 'Criar efeitos visuais em apresentações', 0),
(178, 'Exclusivamente manutenção de hardware', 0),
(178, 'Apenas edição de documentos', 0),
(178, 'Desenvolvimento de soluções inovadoras e sustentáveis', 1),
(178, 'Somente instalação de redes locais', 0),
(179, 'Configurar bancos de dados relacionais', 0),
(179, 'Criar autenticação em APIs', 0),
(179, 'Organizar protocolos de internet', 0),
(179, 'Explicar detalhadamente características de um projeto', 1),
(180, 'Clareza, organização e domínio do tema', 1),
(180, 'Uso excessivo de animações', 0),
(180, 'Apenas leitura dos slides', 0),
(180, 'Configuração de sistemas operacionais', 0),
(181, 'DML', 1),
(181, 'DDL', 0),
(181, 'TCL', 0),
(181, 'DCL', 0),
(182, 'UPDATE', 0),
(182, 'DELETE', 0),
(182, 'INSERT', 1),
(182, 'SELECT', 0),
(183, 'DML', 0),
(183, 'DQL', 1),
(183, 'DCL', 0),
(183, 'TCL', 0),
(184, 'INSERT', 0),
(184, 'UPDATE', 0),
(184, 'SELECT', 0),
(184, 'DELETE', 1),
(185, 'Cancelar alterações', 0),
(185, 'Salvar alterações realizadas', 1),
(185, 'Excluir tabelas', 0),
(185, 'Criar banco de dados', 0),
(186, 'Inserir registros', 0),
(186, 'Consultar dados', 0),
(186, 'Alterar dados existentes', 1),
(186, 'Excluir tabelas', 0),
(187, 'Excluir registros duplicados', 0),
(187, 'Ordenar resultados de uma consulta', 1),
(187, 'Criar tabelas', 0),
(187, 'Fazer backup do banco', 0),
(188, 'COUNT', 1),
(188, 'SUM', 0),
(188, 'AVG', 0),
(188, 'MAX', 0),
(189, 'Unir tabelas mostrando apenas dados relacionados', 1),
(189, 'Excluir relações entre tabelas', 0),
(189, 'Criar novos bancos de dados', 0),
(189, 'Atualizar várias tabelas ao mesmo tempo', 0),
(190, 'Confirmar alterações', 0),
(190, 'Criar índices', 0),
(190, 'Desfazer alterações não confirmadas', 1),
(190, 'Excluir banco de dados', 0),
(191, 'Consistência', 0),
(191, 'Isolamento', 0),
(191, 'Durabilidade', 0),
(191, 'Atomicidade', 1),
(192, 'Apenas registros iguais nas duas tabelas', 0),
(192, 'Todos os registros da tabela da esquerda e os correspondentes da direita', 1),
(192, 'Apenas registros da tabela da direita', 0),
(192, 'Somente registros duplicados', 0),
(193, 'Apenas registros relacionados', 0),
(193, 'Atualização automática dos dados', 0),
(193, 'Produto cartesiano entre tabelas', 1),
(193, 'Exclusão de registros repetidos', 0),
(194, 'DIFFERENCE', 0),
(194, 'INTERSECT', 0),
(194, 'JOIN', 0),
(194, 'UNION', 1),
(195, 'Os dados sejam apagados após o uso', 0),
(195, 'As alterações confirmadas permaneçam salvas mesmo após falhas', 1),
(195, 'Apenas um usuário utilize o banco por vez', 0),
(195, 'Consultas sejam executadas mais rapidamente', 0),
(196, 'Um sistema desenvolvido apenas para jogos', 0),
(196, 'Um sistema dedicado a executar funções específicas', 1),
(196, 'Um tipo de banco de dados', 0),
(196, 'Um programa utilizado apenas em computadores', 0),
(197, 'Processador', 0),
(197, 'Capacitor', 0),
(197, 'Protoboard', 1),
(197, 'Monitor', 0),
(198, 'main()', 0),
(198, 'digitalRead()', 0),
(198, 'setup()', 0),
(198, 'loop()', 1),
(199, 'analogWrite()', 0),
(199, 'pinMode()', 1),
(199, 'delay()', 0),
(199, 'micros()', 0),
(200, 'Armazenar dados', 0),
(200, 'Processar informações', 0),
(200, 'Emitir luz', 1),
(200, 'Amplificar sinais', 0),
(201, 'Ler sinais analógicos', 0),
(201, 'Configurar timers', 0),
(201, 'Enviar sinais digitais para um pino', 1),
(201, 'Reiniciar o microcontrolador', 0),
(202, 'Ler sinais analógicos', 1),
(202, 'Criar números aleatórios', 0),
(202, 'Desligar sensores', 0),
(202, 'Configurar botões', 0),
(203, 'Condição', 0),
(203, 'Repetição', 1),
(203, 'Variável', 0),
(203, 'Biblioteca', 0),
(204, 'Ler sensores digitais', 0),
(204, 'Gerar sons', 0),
(204, 'Criar pausas na execução do programa', 1),
(204, 'Configurar portas analógicas', 0),
(205, 'Desenvolvimento apenas de softwares empresariais', 0),
(205, 'Criação prática de projetos tecnológicos', 1),
(205, 'Exclusão de componentes eletrônicos', 0),
(205, 'Uso exclusivo de computadores antigos', 0),
(206, 'Transformar sinais analógicos em valores digitais', 1),
(206, 'Aumentar a memória do microcontrolador', 0),
(206, 'Criar interfaces gráficas', 0),
(206, 'Excluir sinais elétricos', 0),
(207, 'A temperatura do sistema', 0),
(207, 'O tempo em milissegundos desde o início da execução', 1),
(207, 'A quantidade de memória disponível', 0),
(207, 'O número de portas digitais', 0),
(208, 'Organizar componentes físicos apenas', 0),
(208, 'Substituir microcontroladores', 0),
(208, 'Facilitar o uso de sensores e recursos específicos', 1),
(208, 'Eliminar o uso de funções', 0),
(209, 'Dispositivos conectados trocando dados pela internet', 1),
(209, 'Uso exclusivo de computadores sem rede', 0),
(209, 'Sistemas sem sensores', 0),
(209, 'Eliminação de comunicação entre dispositivos', 0),
(210, 'Controlar intervalos e medições de tempo', 1),
(210, 'Aumentar o tamanho físico da placa', 0),
(210, 'Excluir bibliotecas automaticamente', 0),
(210, 'Substituir entradas analógicas', 0),
(211, 'Swift', 0),
(211, 'Kotlin', 1),
(211, 'Ionic', 0),
(211, 'Flutter', 0),
(212, 'Exclusivo para iOS', 0),
(212, 'Desktop', 0),
(212, 'Nativo multiplataforma', 1),
(212, 'Banco de dados', 0),
(213, 'Lista', 0),
(213, 'Botão', 0),
(213, 'Imagem', 0),
(213, 'Texto', 1),
(214, 'Criar hardware para celulares', 0),
(214, 'Fornecer ferramentas para desenvolvimento', 1),
(214, 'Excluir aplicativos do aparelho', 0),
(214, 'Formatar dispositivos móveis', 0),
(215, 'Desenvolver bancos de dados', 0),
(215, 'Armazenar componentes físicos', 0),
(215, 'Distribuir aplicativos para usuários', 1),
(215, 'Configurar redes locais', 0),
(216, 'Nativo multiplataforma', 1),
(216, 'Exclusivo para Android', 0),
(216, 'Exclusivo para iOS', 0),
(216, 'Apenas híbrido', 0),
(217, 'Utilizar dados sem conexão com internet', 1),
(217, 'Excluir arquivos automaticamente', 0),
(217, 'Bloquear o uso do aplicativo', 0),
(217, 'Aumentar o tamanho da tela do celular', 0),
(218, 'Melhorar apenas a aparência do app', 0),
(218, 'Controlar acesso a recursos do dispositivo', 1),
(218, 'Criar bancos de dados externos', 0),
(218, 'Excluir notificações do sistema', 0),
(219, 'Uma tela inicial exibida ao abrir o aplicativo', 1),
(219, 'Um banco de dados interno', 0),
(219, 'Um tipo de linguagem mobile', 0),
(219, 'Um sistema operacional', 0),
(220, 'Trocar o sistema operacional do celular', 0),
(220, 'Configurar internet móvel', 0),
(220, 'Controlar a mudança entre telas do aplicativo', 1),
(220, 'Excluir componentes da interface', 0),
(221, 'Java e Swift', 0),
(221, 'Flutter e React Native', 0),
(221, 'Cordova e Ionic', 1),
(221, 'Kotlin e Xamarin', 0),
(222, 'Controla e atualiza informações da interface do aplicativo', 1),
(222, 'Remove permissões automaticamente', 0),
(222, 'Substitui o armazenamento offline', 0),
(222, 'Cria emuladores para celulares', 0),
(223, 'Aumentar a memória do celular', 0),
(223, 'Simular dispositivos para testes de aplicativos', 1),
(223, 'Criar bancos de dados online', 0),
(223, 'Melhorar sinais de internet', 0),
(224, 'Apenas o design da interface', 0),
(224, 'O tempo de bateria do celular', 0),
(224, 'As etapas de execução e funcionamento do aplicativo', 1),
(224, 'A quantidade de usuários do sistema', 0),
(225, 'Necessidade de criar aplicativos separados para cada sistema', 0),
(225, 'Uso exclusivo em computadores', 0),
(225, 'Desenvolvimento mais rápido para diferentes plataformas', 1),
(225, 'Eliminação total do uso de interfaces gráficas', 0),
(226, 'Banco de dados sem estrutura fixa relacional', 1),
(226, 'Linguagem de programação para web', 0),
(226, 'Sistema operacional para servidores', 0),
(226, 'Ferramenta de design gráfico', 0),
(227, 'Redis', 0),
(227, 'MongoDB', 1),
(227, 'Neo4j', 0),
(227, 'Cassandra', 0),
(228, 'Documento', 0),
(228, 'Coluna', 0),
(228, 'Grafo', 0),
(228, 'Chave-valor', 1),
(229, 'Bigtable', 0),
(229, 'CouchDB', 0),
(229, 'Neo4j', 1),
(229, 'MongoDB', 0),
(230, 'Criação, leitura, atualização e exclusão de dados', 1),
(230, 'Compactação de arquivos', 0),
(230, 'Desenvolvimento de hardware', 0),
(230, 'Criação de redes locais', 0),
(231, 'Trabalhar apenas com tabelas fixas', 0),
(231, 'Melhorar escalabilidade e flexibilidade', 1),
(231, 'Eliminar armazenamento de dados', 0),
(231, 'Substituir linguagens de programação', 0),
(232, 'Linhas de uma tabela', 0),
(232, 'Campos numéricos', 0),
(232, 'Tabelas em bancos relacionais', 1),
(232, 'Índices automáticos', 0),
(233, 'Armazenar documentos dentro de outros documentos', 1),
(233, 'Criar tabelas relacionais', 0),
(233, 'Separar todos os dados em servidores diferentes', 0),
(233, 'Utilizar apenas números inteiros', 0),
(234, 'Agregação', 0),
(234, 'Índices', 1),
(234, 'Transações', 0),
(234, 'Map-Reduce', 0),
(235, 'Criação de interfaces gráficas', 0),
(235, 'Desenvolvimento de aplicativos mobile', 0),
(235, 'Processamento de grandes volumes de dados', 1),
(235, 'Exclusão automática de documentos', 0),
(236, 'Consultas analíticas em grandes volumes de dados', 1),
(236, 'Desenvolvimento de jogos', 0),
(236, 'Edição de imagens', 0),
(236, 'Criação de páginas HTML', 0),
(237, 'Grandes volumes de dados processados rapidamente', 1),
(237, 'Pequenos arquivos locais', 0),
(237, 'Criação de interfaces simples', 0),
(237, 'Desenvolvimento de hardware portátil', 0),
(238, 'Garantir consistência nas operações de dados', 1),
(238, 'Criar novas linguagens de programação', 0),
(238, 'Melhorar apenas o design das aplicações', 0),
(238, 'Eliminar índices automaticamente', 0),
(239, 'MongoDB', 0),
(239, 'Neo4j', 0),
(239, 'Redis', 1),
(239, 'Cassandra', 0),
(240, 'Análise e interpretação de dados para gerar conhecimento', 1),
(240, 'Desenvolvimento exclusivo de hardware', 0),
(240, 'Criação de sistemas operacionais', 0),
(240, 'Montagem de redes físicas', 0),
(241, 'Internal Program', 0),
(241, 'Internet Program', 0),
(241, 'Internet Protocol', 1),
(241, 'Integrated Process', 0),
(242, 'FTP', 0),
(242, 'SSH', 0),
(242, 'DNS', 0),
(242, 'HTTP', 1),
(243, 'arp', 0),
(243, 'route', 0),
(243, 'ping', 1),
(243, 'netstat', 0),
(244, 'Traduzir nomes de domínio em endereços IP', 1),
(244, 'Armazenar arquivos', 0),
(244, 'Criar páginas web', 0),
(244, 'Configurar placas de vídeo', 0),
(245, 'FTP', 0),
(245, 'HTTP', 0),
(245, 'DNS', 0),
(245, 'SSH', 1),
(246, 'Dois computadores compartilham hardware físico', 0),
(246, 'Apenas servidores trocam informações', 0),
(246, 'Um dispositivo solicita serviços e outro responde', 1),
(246, 'Não existe comunicação entre dispositivos', 0),
(247, 'Trabalhar apenas com imagens', 0),
(247, 'Garantir entrega confiável de dados', 1),
(247, 'Não utilizar portas', 0),
(247, 'Substituir o protocolo IP', 0),
(248, 'ipconfig', 1),
(248, 'pathping', 0),
(248, 'nslookup', 0),
(248, 'getmac', 0),
(249, 'Criar bancos de dados', 0),
(249, 'Configurar navegadores', 0),
(249, 'Desenvolver aplicativos mobile', 0),
(249, 'Traduzir endereços de rede', 1),
(250, 'Melhorar sinais de internet', 0),
(250, 'Criar páginas HTML', 0),
(250, 'Armazenar informações de sessão do usuário', 1),
(250, 'Substituir servidores web', 0),
(251, 'FTP e DNS', 0),
(251, 'TCP e UDP', 0),
(251, 'NAT e ARP', 0),
(251, 'SSL e TLS', 1),
(252, 'Sucesso na requisição', 0),
(252, 'Recurso não encontrado', 1),
(252, 'Erro interno do servidor', 0),
(252, 'Acesso autorizado', 0),
(253, 'Utiliza criptografia obrigatória', 0),
(253, 'Não trabalha com portas', 0),
(253, 'Não garante entrega confiável dos dados', 1),
(253, 'Funciona apenas na web', 0),
(254, 'Criar páginas HTML', 0),
(254, 'Desenvolver bancos de dados', 0),
(254, 'Configurar impressoras', 0),
(254, 'Capturar e analisar tráfego de rede', 1),
(255, 'O navegador não usa cookies', 0),
(255, 'O protocolo não armazena estado entre requisições', 1),
(255, 'O servidor sempre salva informações do usuário', 0),
(255, 'O HTTP não utiliza cabeçalhos', 0),
(256, 'Sistema operacional mobile', 0),
(256, 'Interface para comunicação entre sistemas', 1),
(256, 'Banco de dados relacional', 0),
(256, 'Linguagem de programação', 0),
(257, 'Comunicação sem fio entre dispositivos', 1),
(257, 'Desenvolver bancos de dados', 0),
(257, 'Editar imagens digitais', 0),
(257, 'Criar páginas web', 0),
(258, 'GPS', 0),
(258, 'Bluetooth', 0),
(258, 'Câmera', 1),
(258, 'Sensor de proximidade', 0),
(259, 'Controle de memória RAM', 0),
(259, 'Criação de tabelas', 0),
(259, 'Edição de textos', 0),
(259, 'Localização e mapas', 1),
(260, 'Redes sociais apenas', 0),
(260, 'Banco de dados', 0),
(260, 'Impressão de documentos', 0),
(260, 'Mensagens de texto', 1),
(261, 'Funcionem apenas offline', 0),
(261, 'Eliminem o uso da internet', 0),
(261, 'Troquem informações com servidores e sistemas externos', 1),
(261, 'Substituam bancos de dados', 0),
(262, 'Apenas envio de mensagens', 0),
(262, 'Comunicação sem internet obrigatoriamente', 0),
(262, 'Troca de dados nos dois sentidos simultaneamente', 1),
(262, 'Apenas recebimento de mensagens', 0),
(263, 'Criar animações', 0),
(263, 'Verificar a identidade do usuário', 1),
(263, 'Editar imagens', 0),
(263, 'Configurar sensores', 0),
(264, 'Melhorar impressões gráficas', 0),
(264, 'Criar bancos de dados', 0),
(264, 'Detectar movimento e orientação do aparelho', 1),
(264, 'Excluir aplicativos automaticamente', 0),
(265, 'Criar bancos de dados relacionais', 0),
(265, 'Configurar roteadores', 0),
(265, 'Desenvolver hardware mobile', 0),
(265, 'Preparar o aplicativo para instalação e distribuição', 1),
(266, 'Comunicação entre aplicativos e equipamentos eletrônicos externos', 1),
(266, 'Substituição de APIs REST', 0),
(266, 'Criação de redes sociais', 0),
(266, 'Exclusão automática de arquivos', 0),
(267, 'SMTP', 0),
(267, 'FTP', 0),
(267, 'SSH', 0),
(267, 'HTTP', 1),
(268, 'Desenvolver placas eletrônicas', 0),
(268, 'Criar imagens vetoriais', 0),
(268, 'Melhorar a segurança de acesso aos sistemas', 1),
(268, 'Configurar impressoras', 0),
(269, 'Serviços de geolocalização e APIs de mapas', 1),
(269, 'Planilhas eletrônicas', 0),
(269, 'Sistemas de impressão', 0),
(269, 'Cabos HDMI', 0),
(270, 'Monitores CRT', 0),
(270, 'Sensores como acelerômetro e giroscópio', 1),
(270, 'Impressoras térmicas', 0),
(270, 'Fontes ATX', 0),
(271, 'Single Page Application', 1),
(271, 'Simple Program Access', 0),
(271, 'System Page Application', 0),
(271, 'Secure Page Area', 0),
(272, 'Criação de banco de dados', 0),
(272, 'Configuração de hardware', 0),
(272, 'Navegação entre páginas e componentes', 1),
(272, 'Desenvolvimento de drivers', 0),
(273, 'Arquivos de áudio', 0),
(273, 'Sistemas operacionais', 0),
(273, 'Protocolos de rede', 0),
(273, 'Partes reutilizáveis da interface', 1),
(274, 'Cookies', 1),
(274, 'Impressoras', 0),
(274, 'Compiladores', 0),
(274, 'Switches', 0),
(275, 'Criar imagens digitais', 0),
(275, 'Comunicação entre aplicações e serviços', 1),
(275, 'Configurar redes locais', 0),
(275, 'Desenvolver hardware', 0),
(276, 'Criar bancos de dados relacionais', 0),
(276, 'Controlar dados e comportamento da interface', 1),
(276, 'Configurar roteadores físicos', 0),
(276, 'Editar arquivos multimídia', 0),
(277, 'Processo de criar redes de computadores', 0),
(277, 'Processo de configurar servidores FTP', 0),
(277, 'Processo de exibir conteúdo visual no navegador', 1),
(277, 'Processo de montar hardware', 0),
(278, 'Garantir que os dados preenchidos estejam corretos', 1),
(278, 'Criar sistemas operacionais', 0),
(278, 'Melhorar velocidade da internet', 0),
(278, 'Configurar impressoras', 0),
(279, 'Controle de hardware', 0),
(279, 'Desenvolvimento de drivers', 0),
(279, 'Criação de placas eletrônicas', 0),
(279, 'Gerenciamento de conteúdo digital', 1),
(280, 'Excluir automaticamente cookies', 0),
(280, 'Criar bancos de dados NoSQL', 0),
(280, 'Configurar sensores físicos', 0),
(280, 'Manter informações temporárias do usuário durante o uso do sistema', 1),
(281, 'Verificar identidade e segurança de acesso', 1),
(281, 'Editar componentes gráficos', 0),
(281, 'Criar tabelas relacionais', 0),
(281, 'Melhorar desempenho de hardware', 0),
(282, 'Criar animações', 0),
(282, 'Confirmar a identidade do usuário', 1),
(282, 'Desenvolver bancos de dados', 0),
(282, 'Configurar dispositivos físicos', 0),
(283, 'Velocidade da conexão de rede', 0),
(283, 'Configuração de periféricos', 0),
(283, 'Quais recursos cada usuário pode acessar', 1),
(283, 'Tipos de memória RAM', 0),
(284, 'Criar interfaces gráficas', 0),
(284, 'Configurar servidores físicos', 0),
(284, 'Montar redes locais', 0),
(284, 'Verificar automaticamente o funcionamento do sistema', 1),
(285, 'Requisições HTTP', 1),
(285, 'Cabos HDMI', 0),
(285, 'Protocolos Bluetooth apenas', 0),
(285, 'Linguagem Assembly', 0),
(286, 'Impressoras térmicas', 0),
(286, 'Cabos de rede', 0),
(286, 'Sensores como acelerômetro e giroscópio', 1),
(286, 'Processadores gráficos externos', 0),
(287, 'Serviços de geolocalização', 1),
(287, 'Planilhas eletrônicas', 0),
(287, 'Editores de imagem', 0),
(287, 'Compiladores de código', 0),
(288, 'Impressoras de rede', 0),
(288, 'Sistemas embarcados', 0),
(288, 'Lojas de aplicativos digitais', 1),
(288, 'Linguagens de marcação', 0),
(289, 'Linguagem usada apenas em jogos', 0),
(289, 'Linguagem usada em situações profissionais e acadêmicas', 1),
(289, 'Linguagem com gírias e abreviações', 0),
(289, 'Linguagem sem regras gramaticais', 0),
(290, 'Programa de edição de imagens', 0),
(290, 'Banco de dados empresarial', 0),
(290, 'Documento com experiências e qualificações profissionais', 1),
(290, 'Sistema operacional', 0),
(291, 'Receita médica', 0),
(291, 'Panfleto publicitário', 0),
(291, 'Cartaz informativo', 0),
(291, 'Memorando', 1),
(292, 'Ligação adequada entre partes do texto', 1),
(292, 'Quantidade de páginas de um texto', 0),
(292, 'Uso exclusivo de palavras técnicas', 0),
(292, 'Organização de imagens em slides', 0),
(293, 'Texto literário de ficção', 0),
(293, 'Documento que apresenta informações técnicas de forma organizada', 1),
(293, 'Página inicial de um site', 0),
(293, 'Sistema de armazenamento em nuvem', 0),
(294, 'Desenvolver jogos digitais', 0),
(294, 'Configurar computadores', 0),
(294, 'Identificar informações importantes em textos técnicos', 1),
(294, 'Criar bancos de dados', 0),
(295, 'Equipamentos de informática', 0),
(295, 'Elementos relacionados à estrutura da língua', 1),
(295, 'Sistemas operacionais', 0),
(295, 'Protocolos de rede', 0),
(296, 'Destacar os temas principais do conteúdo', 1),
(296, 'Decorar o texto visualmente', 0),
(296, 'Aumentar o tamanho do documento', 0),
(296, 'Substituir referências bibliográficas', 0),
(297, 'Uso obrigatório de gráficos', 0),
(297, 'Quantidade de linhas do documento', 0),
(297, 'Organização de imagens digitais', 0),
(297, 'Relação lógica e compreensível entre as ideias do texto', 1),
(298, 'Criar contratos digitais', 0),
(298, 'Elaborar planilhas financeiras', 0),
(298, 'Apresentar o candidato e demonstrar interesse pela vaga', 1),
(298, 'Configurar sistemas operacionais', 0),
(299, 'Uso de linguagem objetiva, clara e especializada', 1),
(299, 'Uso predominante de linguagem informal', 0),
(299, 'Presença obrigatória de ilustrações artísticas', 0),
(299, 'Estrutura baseada apenas em diálogos', 0),
(300, 'Criar efeitos visuais em apresentações', 0),
(300, 'Configurar aplicativos mobile', 0),
(300, 'Identificar as fontes utilizadas em um trabalho', 1),
(300, 'Desenvolver interfaces gráficas', 0),
(301, 'Explicar termos específicos de determinada área', 1),
(301, 'Organizar imagens digitais', 0),
(301, 'Configurar redes de computadores', 0),
(301, 'Criar bancos de dados relacionais', 0),
(302, 'Melhorar velocidade da internet', 0),
(302, 'Organizar conteúdo, tempo e recursos da apresentação', 1),
(302, 'Desenvolver sistemas embarcados', 0),
(302, 'Configurar servidores web', 0),
(303, 'O design visual do documento', 0),
(303, 'O tamanho do arquivo digital', 0),
(303, 'A velocidade de processamento do computador', 0),
(303, 'Se as informações são seguras, corretas e confiáveis', 1),
(304, 'Criar componentes físicos', 0),
(304, 'Melhorar a qualidade e identificar falhas no sistema', 1),
(304, 'Desenvolver hardware', 0),
(304, 'Configurar redes locais', 0),
(305, 'Velocidade de processamento', 0),
(305, 'Capacidade de armazenar arquivos', 0),
(305, 'Facilidade de entender o código-fonte', 1),
(305, 'Uso obrigatório de gráficos', 0),
(306, 'Exclusão automática de funções', 0),
(306, 'Criação de bancos de dados', 0),
(306, 'Desenvolvimento de sistemas operacionais', 0),
(306, 'Aproveitamento de partes do código em outros projetos', 1),
(307, 'Organizar visualmente o código-fonte', 1),
(307, 'Melhorar conexão com internet', 0),
(307, 'Configurar servidores', 0),
(307, 'Criar tabelas relacionais', 0),
(308, 'Tipo de linguagem de programação', 0),
(308, 'Qualidade da interação do usuário com o sistema', 1),
(308, 'Modelo de banco de dados', 0),
(308, 'Sistema de autenticação', 0),
(309, 'Testes de velocidade da internet', 0),
(309, 'Testes que verificam se o sistema funciona conforme esperado', 1),
(309, 'Testes de hardware físico', 0),
(309, 'Testes de impressão gráfica', 0),
(310, 'Apenas manualmente', 0),
(310, 'Somente em servidores físicos', 0),
(310, 'Automaticamente por ferramentas e scripts', 1),
(310, 'Apenas em aplicativos mobile', 0),
(311, 'Facilidade de uso e interação do sistema', 1),
(311, 'Velocidade da memória RAM', 0),
(311, 'Estrutura de redes de computadores', 0),
(311, 'Capacidade de impressão', 0),
(312, 'Desenvolver sem realizar testes', 0),
(312, 'Utilizar apenas testes manuais', 0),
(312, 'Criar bancos de dados primeiro', 0),
(312, 'Criar testes antes do desenvolvimento do código', 1),
(313, 'Dois computadores compartilham hardware', 0),
(313, 'Dois programadores trabalham juntos no mesmo código', 1),
(313, 'Dois servidores utilizam o mesmo IP', 0),
(313, 'Dois bancos de dados são conectados', 0),
(314, 'Excluir funcionalidades do sistema', 0),
(314, 'Melhorar a estrutura do código sem alterar seu funcionamento', 1),
(314, 'Criar bancos de dados NoSQL', 0),
(314, 'Alterar o hardware do computador', 0),
(315, 'Velocidade da internet', 0),
(315, 'Apenas o design das telas', 0),
(315, 'A comunicação entre diferentes partes do sistema', 1),
(315, 'Configuração de periféricos', 0),
(316, 'Desempenho, segurança e confiabilidade', 1),
(316, 'Apenas aparência visual', 0),
(316, 'Estrutura de textos técnicos', 0),
(316, 'Organização de arquivos locais', 0),
(317, 'Qualidade e maturidade de processos de software', 1),
(317, 'Desenvolvimento de hardware', 0),
(317, 'Criação de sistemas operacionais', 0),
(317, 'Configuração de redes sociais', 0),
(318, 'O software funcione sem internet', 0),
(318, 'O sistema utilize apenas banco de dados relacional', 0),
(318, 'O código tenha apenas funções matemáticas', 0),
(318, 'O produto atende às necessidades e requisitos definidos', 1),
(319, 'Relatório', 0),
(319, 'Reunião', 1),
(319, 'Documento', 0),
(319, 'Manual', 0),
(320, 'Relatório técnico', 1),
(320, 'Carta comercial', 0),
(320, 'Manual de instruções', 0),
(320, 'Glossário informal', 0),
(321, 'Linha de código', 0),
(321, 'Prazo final', 1),
(321, 'Documento técnico', 0),
(321, 'Glossário', 0),
(322, 'Entrevista de emprego', 1),
(322, 'Relatório de trabalho', 0),
(322, 'Carta comercial', 0),
(322, 'Manual técnico', 0),
(323, 'Resumo executivo', 1),
(323, 'Manual técnico', 0),
(323, 'Glossário científico', 0),
(323, 'Correspondência administrativa', 0),
(324, 'Capacidade de compreender o outro', 1),
(324, 'Banco de dados', 0),
(324, 'Hardware', 0),
(324, 'Software', 0),
(325, 'Uso sustentável dos recursos naturais', 1),
(325, 'Criação de variáveis', 0),
(325, 'Compilação de programas', 0),
(325, 'Uso de software livre', 0),
(326, 'Conjunto de práticas para garantir conformidade legal e ética', 1),
(326, 'Banco de dados', 0),
(326, 'Hardware', 0),
(326, 'Software', 0),
(327, 'Quantidade de pixels por área', 1),
(327, 'Tipo de fonte', 0),
(327, 'Banco de dados', 0),
(327, 'Hardware', 0),
(328, 'Modelo visual de apresentação de projeto', 1),
(328, 'Banco de dados', 0),
(328, 'Hardware', 0),
(328, 'Texto técnico', 0),
(329, 'Design de interface do usuário', 1),
(329, 'Banco de dados', 0),
(329, 'Hardware', 0),
(329, 'Software de rede', 0),
(330, 'Criar título principal', 1),
(330, 'Criar tabela', 0),
(330, 'Criar imagem', 0),
(330, 'Criar link', 0),
(331, 'Definir espaçamento externo de elementos', 1),
(331, 'Definir cor de fundo', 0),
(331, 'Definir tamanho da fonte', 0),
(331, 'Definir borda', 0),
(332, 'Técnica para atualizar páginas sem recarregar', 1),
(332, 'Banco de dados relacional', 0),
(332, 'Hardware', 0),
(332, 'Software de rede', 0),
(333, 'Unidade central de processamento de dados', 1),
(333, 'Banco de dados', 0),
(333, 'Memória RAM', 0),
(333, 'Rede', 0),
(334, 'Sistema de proteção contra acessos não autorizados', 1),
(334, 'Banco de dados', 0),
(334, 'Hardware de entrada', 0),
(334, 'Software de edição', 0),
(335, 'Rede privada criada sobre a internet para segurança', 1),
(335, 'Banco de dados relacional', 0),
(335, 'Hardware de rede', 0),
(335, 'Software de edição', 0),
(336, 'Outlook', 1),
(336, 'Word', 0),
(336, 'Excel', 0),
(336, 'PowerPoint', 0),
(337, 'Inserir gráfico', 1),
(337, 'Filtro', 0),
(337, 'Classificação', 0),
(337, 'Validação', 0),
(338, 'Gravação de apresentação', 1),
(338, 'Layout', 0),
(338, 'Cabeçalho', 0),
(338, 'Rodapé', 0),
(339, 'Unidade de armazenamento dentro de uma tabela', 1),
(339, 'Hardware', 0),
(339, 'Software', 0),
(339, 'Rede', 0),
(340, 'INSERT', 1),
(340, 'UPDATE', 0),
(340, 'DELETE', 0),
(340, 'SELECT', 0),
(341, 'Conjunto de operações que devem ser executadas de forma atômica', 1),
(341, 'Banco de dados relacional', 0),
(341, 'Hardware', 0),
(341, 'Software de rede', 0),
(342, 'Representação textual simplificada de algoritmos', 1),
(342, 'Banco de dados', 0),
(342, 'Hardware', 0),
(342, 'Software', 0),
(343, 'Bloco de código que executa uma tarefa específica', 1),
(343, 'Banco de dados', 0),
(343, 'Hardware', 0),
(343, 'Software de rede', 0),
(344, 'Medida de desempenho em tempo e espaço', 1),
(344, 'Banco de dados relacional', 0),
(344, 'Hardware', 0),
(344, 'Software de edição', 0),
(345, 'Define desempenho, segurança e usabilidade', 1),
(345, 'Define apenas custos do projeto', 0),
(345, 'Define número de funcionários', 0),
(345, 'Define linguagens de programação', 0),
(346, 'Diagrama de classes', 0),
(346, 'Diagrama de casos de uso', 1),
(346, 'Diagrama de sequência', 0),
(346, 'Diagrama de pacotes', 0),
(347, 'Criação de modelos iniciais para validar ideias', 1),
(347, 'Exclusão de requisitos', 0),
(347, 'Criação de hardware', 0),
(347, 'Compilação de código', 0),
(348, 'Daily Scrum', 1),
(348, 'Sprint Review', 0),
(348, 'Sprint Planning', 0),
(348, 'Retrospectiva', 0),
(349, 'Parte funcional entregue ao final da Sprint', 1),
(349, 'Exclusão de requisitos', 0),
(349, 'Criação de diagramas UML', 0),
(349, 'Documentação de hardware', 0),
(350, 'Função que define comportamento de um objeto', 1),
(350, 'Banco de dados relacional', 0),
(350, 'Hardware', 0),
(350, 'Interface gráfica', 0),
(351, 'Contrato que define métodos sem implementação', 1),
(351, 'Banco de dados', 0),
(351, 'Hardware', 0),
(351, 'Classe abstrata', 0),
(352, 'Princípio que reduz acoplamento entre classes', 1),
(352, 'Exclusão de atributos duplicados', 0),
(352, 'Criação de variáveis globais', 0),
(352, 'Uso exclusivo de herança múltipla', 0),
(353, 'CREATE TABLE', 1),
(353, 'INSERT', 0),
(353, 'UPDATE', 0),
(353, 'DELETE', 0),
(354, 'GROUP BY', 1),
(354, 'ORDER BY', 0),
(354, 'HAVING', 0),
(354, 'WHERE', 0),
(355, 'Eliminação de dependências transitivas', 1),
(355, 'Exclusão de tabelas duplicadas', 0),
(355, 'Criação de índices automáticos', 0),
(355, 'Backup de dados', 0),
(356, 'Swift', 1),
(356, 'Kotlin', 0),
(356, 'Java', 0),
(356, 'Dart', 0),
(357, 'Push Notification', 1),
(357, 'Splash Screen', 0),
(357, 'Roteamento', 0),
(357, 'Permissões', 0),
(358, 'Guardar dados em servidores externos acessíveis pela internet', 1),
(358, 'Exclusão automática de arquivos', 0),
(358, 'Criação de tabelas locais', 0),
(358, 'Backup apenas offline', 0),
(359, 'Detalhamento de metas menores dentro do objetivo geral', 1),
(359, 'Cronograma de execução', 0),
(359, 'Justificativa do projeto', 0),
(359, 'Hipótese principal', 0),
(360, 'Conjunto de métodos e técnicas para conduzir a pesquisa', 1),
(360, 'Apenas cronograma de atividades', 0),
(360, 'Exclusão de hipóteses', 0),
(360, 'Criação de tabelas', 0),
(361, 'Base de conceitos e estudos que sustentam a pesquisa', 1),
(361, 'Exclusão de dados duplicados', 0),
(361, 'Criação de variáveis', 0),
(361, 'Organização de cronograma', 0),
(362, 'Cassandra', 0),
(362, 'Neo4j', 1),
(362, 'Redis', 0),
(362, 'MongoDB', 0),
(363, 'Criptografia de dados', 0),
(363, 'Divisão de dados em múltiplos servidores', 1),
(363, 'Exclusão automática de documentos', 0),
(363, 'Backup em nuvem', 0),

(364, 'Uso exclusivo de tabelas', 0),
(364, 'Flexibilidade para dados não estruturados', 1),
(364, 'Necessidade de chaves primárias', 0),
(364, 'Restrição a consultas SQL', 0),
(365, 'insertOne', 0),
(365, 'find', 1),
(365, 'updateOne', 0),
(365, 'deleteOne', 0),
(366, 'MapReduce', 0),
(366, 'CAP Theorem', 1),
(366, 'CRUD', 0),
(366, 'DNS', 0),
(367, 'SMTP', 1),
(367, 'POP3', 0),
(367, 'IMAP', 0),
(367, 'HTTPS', 0),
(368, 'Criptografia SSL/TLS', 1),
(368, 'Compressão de pacotes', 0),
(368, 'Backup automático', 0),
(368, 'Tradução de IPs', 0),
(369, 'ping', 0),
(369, 'netstat', 1),
(369, 'tracert', 0),
(369, 'nslookup', 0),
(370, '200', 0),
(370, '301', 1),
(370, '403', 0),
(370, '500', 0),
(371, 'DNS', 1),
(371, 'ARP', 0),
(371, 'ICMP', 0),
(371, 'DHCP', 0),
(372, 'Internet Data Service', 0),
(372, 'Intrusion Detection System', 1),
(372, 'Internal Data Security', 0),
(372, 'Information Defense Suite', 0),
(373, 'NMAP', 1),
(373, 'Wireshark', 0),
(373, 'Metasploit', 0),
(373, 'Nessus', 0),
(374, 'Engenharia social', 1),
(374, 'SQL Injection', 0),
(374, 'DoS', 0),
(374, 'Phishing', 0),
(375, 'HTTP', 0),
(375, 'TLS', 1),
(375, 'FTP', 0),
(375, 'DNS', 0),
(376, 'Tríade CIA', 1),
(376, 'Hashing', 0),
(376, 'Criptografia simétrica', 0),
(376, 'Autenticação multifator', 0),
(377, 'Bluetooth', 0),
(377, 'Câmera', 1),
(377, 'GPS', 0),
(377, 'Sensor de proximidade', 0),
(378, 'FTP', 0),
(378, 'HTTP', 1),
(378, 'SMTP', 0),
(378, 'DNS', 0),
(379, 'Sensor de luz', 0),
(379, 'GPS', 1),
(379, 'Bluetooth', 0),
(379, 'Câmera', 0),
(380, 'OAuth', 1),
(380, 'DNS', 0),
(380, 'TCP', 0),
(380, 'CRUD', 0),
(381, 'REST', 0),
(381, 'WebSockets', 1),
(381, 'FTP', 0),
(381, 'NAT', 0),
(382, 'SPA', 1),
(382, 'CMS', 0),
(382, 'CRUD', 0),
(382, 'API', 0),
(383, '<div>', 0),
(383, '<form>', 1),
(383, '<span>', 0),
(383, '<table>', 0),
(384, 'Angular', 1),
(384, 'MySQL', 0),
(384, 'Redis', 0),
(384, 'Wireshark', 0),
(385, 'Hashing', 0),
(385, 'Validação de formulários', 1),
(385, 'CRUD', 0),
(385, 'Indexação', 0),
(386, 'CSP', 1),
(386, 'CRUD', 0),
(386, 'DNS', 0),
(386, 'SSL', 0),
(387, 'Clareza e lógica na construção das ideias', 1),
(387, 'Uso de palavras difíceis', 0),
(387, 'Repetição de termos técnicos', 0),
(387, 'Exclusão de conectivos', 0),
(388, 'Memorando', 1),
(388, 'Relatório técnico', 0),
(388, 'Carta comercial', 0),
(388, 'Contrato', 0),
(389, 'Sintaxe', 0),
(389, 'Vocabulário', 0),
(389, 'Contexto sociocultural', 1),
(389, 'Pontuação', 0),
(390, 'Memorial descritivo', 1),
(390, 'Carta-currículo', 0),
(390, 'Aviso', 0),
(390, 'Recibo', 0),
(391, 'Leitura instrumental', 0),
(391, 'Leitura especializada', 1),
(391, 'Leitura dinâmica', 0),
(391, 'Leitura superficial', 0),
(392, 'Indentação', 1),
(392, 'Criptografia', 0),
(392, 'Hashing', 0),
(392, 'Indexação', 0),
(393, 'UX', 1),
(393, 'CRUD', 0),
(393, 'SQL', 0),
(393, 'API', 0),
(394, 'Teste de aceitação', 1),
(394, 'Teste unitário', 0),
(394, 'Teste exploratório', 0),
(394, 'Teste de integração', 0),
(395, 'Refatoração', 0),
(395, 'Programação em par', 1),
(395, 'Reutilização de código', 0),
(395, 'Teste de usabilidade', 0),
(396, 'CMMI', 0),
(396, 'MPS.br', 1),
(396, 'ISO 27001', 0),
(396, 'OWASP', 0);

-- Stored Procedures --
DELIMITER / /


CREATE PROCEDURE CadastrarUsuario(
    IN p_nome VARCHAR(100),
    IN p_email VARCHAR(100),
    IN p_senha VARCHAR(255)
)
BEGIN
    DECLARE v_existe INT;

    SELECT COUNT(*) INTO v_existe
    FROM usuario
    WHERE email = p_email;

    IF v_existe > 0 THEN
        SELECT 'Email já cadastrado!' AS mensagem;

    ELSE
        INSERT INTO usuario(nome, email, senha, pontuacao)
        VALUES (p_nome, p_email, p_senha, 0);

        SELECT 'Usuário cadastrado com sucesso!' AS mensagem;
    END IF;

END;
CREATE PROCEDURE AtualizarQuiz(IN p_id INT, IN p_pontuacao INT) BEGIN
UPDATE
    quiz
SET
    pontuacao = p_pontuacao
WHERE
    id = p_id;
END / / CREATE PROCEDURE DeleteQuiz(IN p_id INT) BEGIN
DELETE FROM
    quiz
WHERE
    id = p_id;
END / / CREATE PROCEDURE SelectQuiz(IN p_id INT) BEGIN
SELECT
    *
FROM
    quiz
WHERE
    id = p_id;
END / / CREATE PROCEDURE Escolher_Disciplina_por_Curso(IN p_id_curso INT) BEGIN
SELECT
    id,
    nome,
    sigla
FROM
    disciplina
WHERE
    id_curso = p_id_curso;
END / / CREATE PROCEDURE Consultar_disciplina_por_modulo (IN p_id_curso INT, IN p_modulo INT) BEGIN
SELECT
    nome,
    sigla
FROM
    disciplina
WHERE
    id_curso = p_id_curso
    and modulo = p_modulo;
END / / CREATE PROCEDURE Escolher_uma_Alternativa_Questao(IN p_id_questao INT) BEGIN
SELECT
    id,
    enunciado,
    correta
FROM
    alternativa
WHERE
    id_questao = p_id_questao;
END / / CREATE PROCEDURE Escolher_cinco_questoes_Aleatoria_Disciplina(IN p_id_disciplina INT) BEGIN
SELECT
    id,
    enunciado,
    pontuacao
FROM
    questao
WHERE
    id_disciplina = p_id_disciplina
ORDER BY
    RAND()
LIMIT
    5;
END / / CREATE PROCEDURE Escolher_Quizes_de_Usuario(IN p_id_usuario INT) BEGIN
SELECT
    *
FROM
    quiz
WHERE
    id_usuario = p_id_usuario
ORDER BY
    data DESC;
END / / CREATE PROCEDURE escolher_Usuario_ordenados_por_pontos() BEGIN
SELECT
    id,
    nome,
    pontuacao
FROM
    usuario
ORDER BY
    pontuacao DESC;
END / / CREATE PROCEDURE Verificar_Se_Login_Existe_e_Senha_Bate(
    IN p_email VARCHAR(100),
    IN p_senha VARCHAR(255)
) BEGIN
SELECT
    id,
    nome,
    email
FROM
    usuario
WHERE
    email = p_email
    AND senha = p_senha;
END / / CREATE PROCEDURE Verificar_Login_Existente(IN p_email VARCHAR(100)) BEGIN
SELECT
    COUNT(*) AS existe
FROM
    usuario
WHERE
    email = p_email;
END / / CREATE PROCEDURE AtualizarPontuacaoUsuario(
    IN p_id_usuario INT,
    IN p_pontos_novos INT
) BEGIN
UPDATE
    usuario
SET
    pontuacao = pontuacao + p_pontos_novos
WHERE
    id = p_id_usuario;
END / / CREATE PROCEDURE RankingUsuarios() BEGIN
SELECT
    nome,
    pontuacao
FROM
    usuario
ORDER BY
    pontuacao DESC
LIMIT
    10;
END / / CREATE PROCEDURE RankingUsuariosComInsignia() BEGIN
SELECT
    nome,
    pontuacao,
    CASE
        WHEN pontuacao >= 1000 THEN 'Diamante'
        WHEN pontuacao >= 500 THEN 'Ouro'
        WHEN pontuacao >= 200 THEN 'Prata'
        ELSE 'Bronze'
    END AS insignia
FROM
    usuario
ORDER BY
    pontuacao DESC;
END // DELIMITER //